#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysiotherapyCare.Model.VisitPatientCare
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhysiotherapyCare")]
	public partial class DataClassesVisitPatientCareDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_VisitPatientCare(TBL_VisitPatientCare instance);
    partial void UpdateTBL_VisitPatientCare(TBL_VisitPatientCare instance);
    partial void DeleteTBL_VisitPatientCare(TBL_VisitPatientCare instance);
    #endregion
		
		public DataClassesVisitPatientCareDataContext() : 
				base(global::PhysiotherapyCare.Model.Properties.Settings.Default.PhysiotherapyCareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientCareDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientCareDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientCareDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientCareDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_VisitPatientCare> TBL_VisitPatientCares
		{
			get
			{
				return this.GetTable<TBL_VisitPatientCare>();
			}
		}
		
		public System.Data.Linq.Table<VW_VisitPatientCare> VW_VisitPatientCares
		{
			get
			{
				return this.GetTable<VW_VisitPatientCare>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VisitPatientCareDelete")]
		public int SP_VisitPatientCareDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VisitPatientCareReport")]
		public ISingleResult<SP_VisitPatientCareReportResult> SP_VisitPatientCareReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateStart", DbType="VarChar(10)")] string dateStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateEnd", DbType="VarChar(10)")] string dateEnd, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonthSet", DbType="Bit")] System.Nullable<bool> monthSet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateStart, dateEnd, monthSet);
			return ((ISingleResult<SP_VisitPatientCareReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VisitPatientCareInsert")]
		public int SP_VisitPatientCareInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] ref System.Nullable<long> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Patient_Id", DbType="Int")] System.Nullable<int> patient_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IssueArchive", DbType="NVarChar(10)")] string issueArchive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LetterNo", DbType="VarChar(20)")] string letterNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LetterDate", DbType="VarChar(10)")] string letterDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContractNo", DbType="VarChar(20)")] string contractNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContractDate", DbType="VarChar(10)")] string contractDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Doctor_Id", DbType="Int")] System.Nullable<int> doctor_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierName", DbType="NVarChar(50)")] string carrierName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierFamily", DbType="NVarChar(50)")] string carrierFamily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierNationalCode", DbType="VarChar(10)")] string carrierNationalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierSex", DbType="TinyInt")] System.Nullable<byte> carrierSex, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierBrithDate", DbType="VarChar(10)")] string carrierBrithDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierAddress", DbType="NVarChar(1000)")] string carrierAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierTelHome", DbType="VarChar(50)")] string carrierTelHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierMobile", DbType="VarChar(50)")] string carrierMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bank_Id", DbType="SmallInt")] System.Nullable<short> bank_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardBankNo1", DbType="VarChar(100)")] string cardBankNo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardBankNo2", DbType="VarChar(100)")] string cardBankNo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KinShip_Id", DbType="SmallInt")] System.Nullable<short> kinShip_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientFillAccount", DbType="Bit")] System.Nullable<bool> patientFillAccount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShiftFew", DbType="SmallInt")] System.Nullable<short> shiftFew, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeginDate", DbType="VarChar(10)")] string beginDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="VarChar(10)")] string endDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitStatus_Id", DbType="SmallInt")] System.Nullable<short> visitStatus_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReciveFileDate", DbType="VarChar(10)")] string reciveFileDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(2000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="VarChar(20)")] string changeDateTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, patient_Id, issueArchive, letterNo, letterDate, contractNo, contractDate, doctor_Id, carrierName, carrierFamily, carrierNationalCode, carrierSex, carrierBrithDate, carrierAddress, carrierTelHome, carrierMobile, bank_Id, cardBankNo1, cardBankNo2, kinShip_Id, patientFillAccount, shiftFew, beginDate, endDate, visitStatus_Id, reciveFileDate, description, user_Id, changeDateTime, msgRet);
			id = ((System.Nullable<long>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(29)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VisitPatientCareUpdate")]
		public int SP_VisitPatientCareUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Patient_Id", DbType="Int")] System.Nullable<int> patient_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IssueArchive", DbType="NVarChar(10)")] string issueArchive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LetterNo", DbType="VarChar(20)")] string letterNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LetterDate", DbType="VarChar(10)")] string letterDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContractNo", DbType="VarChar(20)")] string contractNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContractDate", DbType="VarChar(10)")] string contractDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Doctor_Id", DbType="Int")] System.Nullable<int> doctor_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierName", DbType="NVarChar(50)")] string carrierName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierFamily", DbType="NVarChar(50)")] string carrierFamily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierNationalCode", DbType="VarChar(10)")] string carrierNationalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierSex", DbType="TinyInt")] System.Nullable<byte> carrierSex, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierBrithDate", DbType="VarChar(10)")] string carrierBrithDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierAddress", DbType="NVarChar(1000)")] string carrierAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierTelHome", DbType="VarChar(50)")] string carrierTelHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarrierMobile", DbType="VarChar(50)")] string carrierMobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bank_Id", DbType="SmallInt")] System.Nullable<short> bank_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardBankNo1", DbType="VarChar(100)")] string cardBankNo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardBankNo2", DbType="VarChar(100)")] string cardBankNo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KinShip_Id", DbType="SmallInt")] System.Nullable<short> kinShip_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientFillAccount", DbType="Bit")] System.Nullable<bool> patientFillAccount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShiftFew", DbType="SmallInt")] System.Nullable<short> shiftFew, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeginDate", DbType="VarChar(10)")] string beginDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="VarChar(10)")] string endDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitStatus_Id", DbType="SmallInt")] System.Nullable<short> visitStatus_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReciveFileDate", DbType="VarChar(10)")] string reciveFileDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(2000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="VarChar(20)")] string changeDateTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, patient_Id, issueArchive, letterNo, letterDate, contractNo, contractDate, doctor_Id, carrierName, carrierFamily, carrierNationalCode, carrierSex, carrierBrithDate, carrierAddress, carrierTelHome, carrierMobile, bank_Id, cardBankNo1, cardBankNo2, kinShip_Id, patientFillAccount, shiftFew, beginDate, endDate, visitStatus_Id, reciveFileDate, description, user_Id, changeDateTime, msgRet);
			msgRet = ((string)(result.GetParameterValue(29)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VisitPatientCareUpdateWithFieldValue")]
		public int SP_VisitPatientCareUpdateWithFieldValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FieldName", DbType="NVarChar(50)")] string fieldName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FieldValue", DbType="NVarChar(200)")] string fieldValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="VarChar(20)")] string changeDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, fieldName, fieldValue, user_Id, changeDateTime, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VisitPatientCareVisitStatusUpdate")]
		public int SP_VisitPatientCareVisitStatusUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitStatus_Id", DbType="SmallInt")] System.Nullable<short> visitStatus_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="VarChar(20)")] string changeDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitStatus_Id, user_Id, changeDateTime, msgRet);
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_VisitPatientCare")]
	public partial class TBL_VisitPatientCare : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<int> _Patient_Id;
		
		private string _IssueArchive;
		
		private string _LetterNo;
		
		private string _LetterDate;
		
		private string _ContractNo;
		
		private string _ContractDate;
		
		private System.Nullable<int> _Doctor_Id;
		
		private string _CarrierName;
		
		private string _CarrierFamily;
		
		private string _CarrierNationalCode;
		
		private System.Nullable<byte> _CarrierSex;
		
		private string _CarrierBrithDate;
		
		private string _CarrierAddress;
		
		private string _CarrierTelHome;
		
		private string _CarrierMobile;
		
		private System.Nullable<short> _Bank_Id;
		
		private string _CardBankNo1;
		
		private string _CardBankNo2;
		
		private System.Nullable<short> _KinShip_Id;
		
		private System.Nullable<bool> _PatientFillAccount;
		
		private System.Nullable<short> _ShiftFew;
		
		private string _BeginDate;
		
		private string _EndDate;
		
		private System.Nullable<short> _VisitStatus_Id;
		
		private string _ReciveFileDate;
		
		private string _Description;
		
		private System.Nullable<int> _User_Id;
		
		private string _ChangeDateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnPatient_IdChanging(System.Nullable<int> value);
    partial void OnPatient_IdChanged();
    partial void OnIssueArchiveChanging(string value);
    partial void OnIssueArchiveChanged();
    partial void OnLetterNoChanging(string value);
    partial void OnLetterNoChanged();
    partial void OnLetterDateChanging(string value);
    partial void OnLetterDateChanged();
    partial void OnContractNoChanging(string value);
    partial void OnContractNoChanged();
    partial void OnContractDateChanging(string value);
    partial void OnContractDateChanged();
    partial void OnDoctor_IdChanging(System.Nullable<int> value);
    partial void OnDoctor_IdChanged();
    partial void OnCarrierNameChanging(string value);
    partial void OnCarrierNameChanged();
    partial void OnCarrierFamilyChanging(string value);
    partial void OnCarrierFamilyChanged();
    partial void OnCarrierNationalCodeChanging(string value);
    partial void OnCarrierNationalCodeChanged();
    partial void OnCarrierSexChanging(System.Nullable<byte> value);
    partial void OnCarrierSexChanged();
    partial void OnCarrierBrithDateChanging(string value);
    partial void OnCarrierBrithDateChanged();
    partial void OnCarrierAddressChanging(string value);
    partial void OnCarrierAddressChanged();
    partial void OnCarrierTelHomeChanging(string value);
    partial void OnCarrierTelHomeChanged();
    partial void OnCarrierMobileChanging(string value);
    partial void OnCarrierMobileChanged();
    partial void OnBank_IdChanging(System.Nullable<short> value);
    partial void OnBank_IdChanged();
    partial void OnCardBankNo1Changing(string value);
    partial void OnCardBankNo1Changed();
    partial void OnCardBankNo2Changing(string value);
    partial void OnCardBankNo2Changed();
    partial void OnKinShip_IdChanging(System.Nullable<short> value);
    partial void OnKinShip_IdChanged();
    partial void OnPatientFillAccountChanging(System.Nullable<bool> value);
    partial void OnPatientFillAccountChanged();
    partial void OnShiftFewChanging(System.Nullable<short> value);
    partial void OnShiftFewChanged();
    partial void OnBeginDateChanging(string value);
    partial void OnBeginDateChanged();
    partial void OnEndDateChanging(string value);
    partial void OnEndDateChanged();
    partial void OnVisitStatus_IdChanging(System.Nullable<short> value);
    partial void OnVisitStatus_IdChanged();
    partial void OnReciveFileDateChanging(string value);
    partial void OnReciveFileDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUser_IdChanging(System.Nullable<int> value);
    partial void OnUser_IdChanged();
    partial void OnChangeDateTimeChanging(string value);
    partial void OnChangeDateTimeChanged();
    #endregion
		
		public TBL_VisitPatientCare()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Id", DbType="Int")]
		public System.Nullable<int> Patient_Id
		{
			get
			{
				return this._Patient_Id;
			}
			set
			{
				if ((this._Patient_Id != value))
				{
					this.OnPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._Patient_Id = value;
					this.SendPropertyChanged("Patient_Id");
					this.OnPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueArchive", DbType="NVarChar(50)")]
		public string IssueArchive
		{
			get
			{
				return this._IssueArchive;
			}
			set
			{
				if ((this._IssueArchive != value))
				{
					this.OnIssueArchiveChanging(value);
					this.SendPropertyChanging();
					this._IssueArchive = value;
					this.SendPropertyChanged("IssueArchive");
					this.OnIssueArchiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterNo", DbType="VarChar(20)")]
		public string LetterNo
		{
			get
			{
				return this._LetterNo;
			}
			set
			{
				if ((this._LetterNo != value))
				{
					this.OnLetterNoChanging(value);
					this.SendPropertyChanging();
					this._LetterNo = value;
					this.SendPropertyChanged("LetterNo");
					this.OnLetterNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterDate", DbType="VarChar(10)")]
		public string LetterDate
		{
			get
			{
				return this._LetterDate;
			}
			set
			{
				if ((this._LetterDate != value))
				{
					this.OnLetterDateChanging(value);
					this.SendPropertyChanging();
					this._LetterDate = value;
					this.SendPropertyChanged("LetterDate");
					this.OnLetterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNo", DbType="VarChar(20)")]
		public string ContractNo
		{
			get
			{
				return this._ContractNo;
			}
			set
			{
				if ((this._ContractNo != value))
				{
					this.OnContractNoChanging(value);
					this.SendPropertyChanging();
					this._ContractNo = value;
					this.SendPropertyChanged("ContractNo");
					this.OnContractNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractDate", DbType="VarChar(10)")]
		public string ContractDate
		{
			get
			{
				return this._ContractDate;
			}
			set
			{
				if ((this._ContractDate != value))
				{
					this.OnContractDateChanging(value);
					this.SendPropertyChanging();
					this._ContractDate = value;
					this.SendPropertyChanged("ContractDate");
					this.OnContractDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doctor_Id", DbType="Int")]
		public System.Nullable<int> Doctor_Id
		{
			get
			{
				return this._Doctor_Id;
			}
			set
			{
				if ((this._Doctor_Id != value))
				{
					this.OnDoctor_IdChanging(value);
					this.SendPropertyChanging();
					this._Doctor_Id = value;
					this.SendPropertyChanged("Doctor_Id");
					this.OnDoctor_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierName", DbType="NVarChar(50)")]
		public string CarrierName
		{
			get
			{
				return this._CarrierName;
			}
			set
			{
				if ((this._CarrierName != value))
				{
					this.OnCarrierNameChanging(value);
					this.SendPropertyChanging();
					this._CarrierName = value;
					this.SendPropertyChanged("CarrierName");
					this.OnCarrierNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierFamily", DbType="NVarChar(50)")]
		public string CarrierFamily
		{
			get
			{
				return this._CarrierFamily;
			}
			set
			{
				if ((this._CarrierFamily != value))
				{
					this.OnCarrierFamilyChanging(value);
					this.SendPropertyChanging();
					this._CarrierFamily = value;
					this.SendPropertyChanged("CarrierFamily");
					this.OnCarrierFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierNationalCode", DbType="VarChar(10)")]
		public string CarrierNationalCode
		{
			get
			{
				return this._CarrierNationalCode;
			}
			set
			{
				if ((this._CarrierNationalCode != value))
				{
					this.OnCarrierNationalCodeChanging(value);
					this.SendPropertyChanging();
					this._CarrierNationalCode = value;
					this.SendPropertyChanged("CarrierNationalCode");
					this.OnCarrierNationalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierSex", DbType="TinyInt")]
		public System.Nullable<byte> CarrierSex
		{
			get
			{
				return this._CarrierSex;
			}
			set
			{
				if ((this._CarrierSex != value))
				{
					this.OnCarrierSexChanging(value);
					this.SendPropertyChanging();
					this._CarrierSex = value;
					this.SendPropertyChanged("CarrierSex");
					this.OnCarrierSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierBrithDate", DbType="VarChar(10)")]
		public string CarrierBrithDate
		{
			get
			{
				return this._CarrierBrithDate;
			}
			set
			{
				if ((this._CarrierBrithDate != value))
				{
					this.OnCarrierBrithDateChanging(value);
					this.SendPropertyChanging();
					this._CarrierBrithDate = value;
					this.SendPropertyChanged("CarrierBrithDate");
					this.OnCarrierBrithDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierAddress", DbType="NVarChar(1000)")]
		public string CarrierAddress
		{
			get
			{
				return this._CarrierAddress;
			}
			set
			{
				if ((this._CarrierAddress != value))
				{
					this.OnCarrierAddressChanging(value);
					this.SendPropertyChanging();
					this._CarrierAddress = value;
					this.SendPropertyChanged("CarrierAddress");
					this.OnCarrierAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierTelHome", DbType="VarChar(50)")]
		public string CarrierTelHome
		{
			get
			{
				return this._CarrierTelHome;
			}
			set
			{
				if ((this._CarrierTelHome != value))
				{
					this.OnCarrierTelHomeChanging(value);
					this.SendPropertyChanging();
					this._CarrierTelHome = value;
					this.SendPropertyChanged("CarrierTelHome");
					this.OnCarrierTelHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierMobile", DbType="VarChar(50)")]
		public string CarrierMobile
		{
			get
			{
				return this._CarrierMobile;
			}
			set
			{
				if ((this._CarrierMobile != value))
				{
					this.OnCarrierMobileChanging(value);
					this.SendPropertyChanging();
					this._CarrierMobile = value;
					this.SendPropertyChanged("CarrierMobile");
					this.OnCarrierMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_Id", DbType="SmallInt")]
		public System.Nullable<short> Bank_Id
		{
			get
			{
				return this._Bank_Id;
			}
			set
			{
				if ((this._Bank_Id != value))
				{
					this.OnBank_IdChanging(value);
					this.SendPropertyChanging();
					this._Bank_Id = value;
					this.SendPropertyChanged("Bank_Id");
					this.OnBank_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardBankNo1", DbType="VarChar(100)")]
		public string CardBankNo1
		{
			get
			{
				return this._CardBankNo1;
			}
			set
			{
				if ((this._CardBankNo1 != value))
				{
					this.OnCardBankNo1Changing(value);
					this.SendPropertyChanging();
					this._CardBankNo1 = value;
					this.SendPropertyChanged("CardBankNo1");
					this.OnCardBankNo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardBankNo2", DbType="VarChar(100)")]
		public string CardBankNo2
		{
			get
			{
				return this._CardBankNo2;
			}
			set
			{
				if ((this._CardBankNo2 != value))
				{
					this.OnCardBankNo2Changing(value);
					this.SendPropertyChanging();
					this._CardBankNo2 = value;
					this.SendPropertyChanged("CardBankNo2");
					this.OnCardBankNo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinShip_Id", DbType="SmallInt")]
		public System.Nullable<short> KinShip_Id
		{
			get
			{
				return this._KinShip_Id;
			}
			set
			{
				if ((this._KinShip_Id != value))
				{
					this.OnKinShip_IdChanging(value);
					this.SendPropertyChanging();
					this._KinShip_Id = value;
					this.SendPropertyChanged("KinShip_Id");
					this.OnKinShip_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientFillAccount", DbType="Bit")]
		public System.Nullable<bool> PatientFillAccount
		{
			get
			{
				return this._PatientFillAccount;
			}
			set
			{
				if ((this._PatientFillAccount != value))
				{
					this.OnPatientFillAccountChanging(value);
					this.SendPropertyChanging();
					this._PatientFillAccount = value;
					this.SendPropertyChanged("PatientFillAccount");
					this.OnPatientFillAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftFew", DbType="SmallInt")]
		public System.Nullable<short> ShiftFew
		{
			get
			{
				return this._ShiftFew;
			}
			set
			{
				if ((this._ShiftFew != value))
				{
					this.OnShiftFewChanging(value);
					this.SendPropertyChanging();
					this._ShiftFew = value;
					this.SendPropertyChanged("ShiftFew");
					this.OnShiftFewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDate", DbType="VarChar(10)")]
		public string BeginDate
		{
			get
			{
				return this._BeginDate;
			}
			set
			{
				if ((this._BeginDate != value))
				{
					this.OnBeginDateChanging(value);
					this.SendPropertyChanging();
					this._BeginDate = value;
					this.SendPropertyChanged("BeginDate");
					this.OnBeginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="VarChar(10)")]
		public string EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitStatus_Id", DbType="SmallInt")]
		public System.Nullable<short> VisitStatus_Id
		{
			get
			{
				return this._VisitStatus_Id;
			}
			set
			{
				if ((this._VisitStatus_Id != value))
				{
					this.OnVisitStatus_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitStatus_Id = value;
					this.SendPropertyChanged("VisitStatus_Id");
					this.OnVisitStatus_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReciveFileDate", DbType="VarChar(10)")]
		public string ReciveFileDate
		{
			get
			{
				return this._ReciveFileDate;
			}
			set
			{
				if ((this._ReciveFileDate != value))
				{
					this.OnReciveFileDateChanging(value);
					this.SendPropertyChanging();
					this._ReciveFileDate = value;
					this.SendPropertyChanged("ReciveFileDate");
					this.OnReciveFileDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int")]
		public System.Nullable<int> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeDateTime", DbType="VarChar(20)")]
		public string ChangeDateTime
		{
			get
			{
				return this._ChangeDateTime;
			}
			set
			{
				if ((this._ChangeDateTime != value))
				{
					this.OnChangeDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ChangeDateTime = value;
					this.SendPropertyChanged("ChangeDateTime");
					this.OnChangeDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_VisitPatientCare")]
	public partial class VW_VisitPatientCare
	{
		
		private long _Id;
		
		private System.Nullable<int> _Patient_Id;
		
		private string _LetterNo;
		
		private string _LetterDate;
		
		private string _ContractNo;
		
		private string _ContractDate;
		
		private System.Nullable<int> _Doctor_Id;
		
		private string _CarrierName;
		
		private string _CardBankNo1;
		
		private string _CardBankNo2;
		
		private System.Nullable<short> _ShiftFew;
		
		private string _BeginDate;
		
		private string _EndDate;
		
		private string _Description;
		
		private string _DoctorName;
		
		private string _DoctorFamily;
		
		private string _CreateDate;
		
		private string _DosiersNo;
		
		private string _PatientName;
		
		private string _PatientFamily;
		
		private string _ParentName;
		
		private System.Nullable<byte> _Sex;
		
		private string _IDNO;
		
		private string _NationalCode;
		
		private string _PatientTypeStr;
		
		private string _InjuryTypeStr;
		
		private string _BrithDate;
		
		private string _BrithCityName;
		
		private System.Nullable<short> _PercentState;
		
		private string _CityPart;
		
		private System.Nullable<short> _InstitutePart;
		
		private System.Nullable<short> _AddressPart;
		
		private string _Address;
		
		private string _PostalCode;
		
		private string _TelHome;
		
		private string _TelBusiness;
		
		private string _Mobile;
		
		private string _Mobile2;
		
		private string _Email;
		
		private string _AccountNo1;
		
		private string _AccountNo2;
		
		private string _AccountNo3;
		
		private string _CarrierFamily;
		
		private string _CarrierNationalCode;
		
		private System.Nullable<byte> _CarrierSex;
		
		private string _CarrierBrithDate;
		
		private string _CarrierAddress;
		
		private string _CarrierTelHome;
		
		private string _CarrierMobile;
		
		private System.Nullable<bool> _PatientFillAccount;
		
		private System.Nullable<short> _KinShip_Id;
		
		private string _KinShipName;
		
		private string _IssueArchive;
		
		private string _SingleOrNo;
		
		private System.Nullable<short> _VisitStatus_Id;
		
		private string _VisitStatusName;
		
		private System.Nullable<int> _User_Id;
		
		private string _ChangeDateTime;
		
		private string _UsersNameFamily;
		
		private System.Nullable<short> _BonyadAddEven;
		
		private string _SexStr;
		
		private string _MartyrNameFamily;
		
		private string _BonyadAddEvenStr;
		
		private string _CarrierSexStr;
		
		private System.Nullable<short> _Bank_Id;
		
		private System.Nullable<short> _CarrierBank_Id;
		
		private string _CarrierBankName;
		
		private string _BankName;
		
		private string _ReciveFileDate;
		
		private string _BasicInsurance;
		
		private string _CompletionInsurance;
		
		private string _BonyadDosier;
		
		private string _StatePart;
		
		private string _CityState;
		
		public VW_VisitPatientCare()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Id", DbType="Int")]
		public System.Nullable<int> Patient_Id
		{
			get
			{
				return this._Patient_Id;
			}
			set
			{
				if ((this._Patient_Id != value))
				{
					this._Patient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterNo", DbType="VarChar(20)")]
		public string LetterNo
		{
			get
			{
				return this._LetterNo;
			}
			set
			{
				if ((this._LetterNo != value))
				{
					this._LetterNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterDate", DbType="VarChar(10)")]
		public string LetterDate
		{
			get
			{
				return this._LetterDate;
			}
			set
			{
				if ((this._LetterDate != value))
				{
					this._LetterDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractNo", DbType="VarChar(20)")]
		public string ContractNo
		{
			get
			{
				return this._ContractNo;
			}
			set
			{
				if ((this._ContractNo != value))
				{
					this._ContractNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractDate", DbType="VarChar(10)")]
		public string ContractDate
		{
			get
			{
				return this._ContractDate;
			}
			set
			{
				if ((this._ContractDate != value))
				{
					this._ContractDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doctor_Id", DbType="Int")]
		public System.Nullable<int> Doctor_Id
		{
			get
			{
				return this._Doctor_Id;
			}
			set
			{
				if ((this._Doctor_Id != value))
				{
					this._Doctor_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierName", DbType="NVarChar(50)")]
		public string CarrierName
		{
			get
			{
				return this._CarrierName;
			}
			set
			{
				if ((this._CarrierName != value))
				{
					this._CarrierName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardBankNo1", DbType="VarChar(100)")]
		public string CardBankNo1
		{
			get
			{
				return this._CardBankNo1;
			}
			set
			{
				if ((this._CardBankNo1 != value))
				{
					this._CardBankNo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardBankNo2", DbType="VarChar(100)")]
		public string CardBankNo2
		{
			get
			{
				return this._CardBankNo2;
			}
			set
			{
				if ((this._CardBankNo2 != value))
				{
					this._CardBankNo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftFew", DbType="SmallInt")]
		public System.Nullable<short> ShiftFew
		{
			get
			{
				return this._ShiftFew;
			}
			set
			{
				if ((this._ShiftFew != value))
				{
					this._ShiftFew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginDate", DbType="VarChar(10)")]
		public string BeginDate
		{
			get
			{
				return this._BeginDate;
			}
			set
			{
				if ((this._BeginDate != value))
				{
					this._BeginDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="VarChar(10)")]
		public string EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorName", DbType="NVarChar(50)")]
		public string DoctorName
		{
			get
			{
				return this._DoctorName;
			}
			set
			{
				if ((this._DoctorName != value))
				{
					this._DoctorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorFamily", DbType="NVarChar(50)")]
		public string DoctorFamily
		{
			get
			{
				return this._DoctorFamily;
			}
			set
			{
				if ((this._DoctorFamily != value))
				{
					this._DoctorFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
		public string CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo", DbType="NVarChar(100)")]
		public string DosiersNo
		{
			get
			{
				return this._DosiersNo;
			}
			set
			{
				if ((this._DosiersNo != value))
				{
					this._DosiersNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(50)")]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientFamily", DbType="NVarChar(50)")]
		public string PatientFamily
		{
			get
			{
				return this._PatientFamily;
			}
			set
			{
				if ((this._PatientFamily != value))
				{
					this._PatientFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentName", DbType="NVarChar(50)")]
		public string ParentName
		{
			get
			{
				return this._ParentName;
			}
			set
			{
				if ((this._ParentName != value))
				{
					this._ParentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="TinyInt")]
		public System.Nullable<byte> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="NVarChar(50)")]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this._IDNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode", DbType="NVarChar(50)")]
		public string NationalCode
		{
			get
			{
				return this._NationalCode;
			}
			set
			{
				if ((this._NationalCode != value))
				{
					this._NationalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientTypeStr", DbType="NVarChar(200)")]
		public string PatientTypeStr
		{
			get
			{
				return this._PatientTypeStr;
			}
			set
			{
				if ((this._PatientTypeStr != value))
				{
					this._PatientTypeStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InjuryTypeStr", DbType="NVarChar(200)")]
		public string InjuryTypeStr
		{
			get
			{
				return this._InjuryTypeStr;
			}
			set
			{
				if ((this._InjuryTypeStr != value))
				{
					this._InjuryTypeStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate", DbType="NVarChar(50)")]
		public string BrithDate
		{
			get
			{
				return this._BrithDate;
			}
			set
			{
				if ((this._BrithDate != value))
				{
					this._BrithDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithCityName", DbType="NVarChar(50)")]
		public string BrithCityName
		{
			get
			{
				return this._BrithCityName;
			}
			set
			{
				if ((this._BrithCityName != value))
				{
					this._BrithCityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentState", DbType="SmallInt")]
		public System.Nullable<short> PercentState
		{
			get
			{
				return this._PercentState;
			}
			set
			{
				if ((this._PercentState != value))
				{
					this._PercentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityPart", DbType="NVarChar(50)")]
		public string CityPart
		{
			get
			{
				return this._CityPart;
			}
			set
			{
				if ((this._CityPart != value))
				{
					this._CityPart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutePart", DbType="SmallInt")]
		public System.Nullable<short> InstitutePart
		{
			get
			{
				return this._InstitutePart;
			}
			set
			{
				if ((this._InstitutePart != value))
				{
					this._InstitutePart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressPart", DbType="SmallInt")]
		public System.Nullable<short> AddressPart
		{
			get
			{
				return this._AddressPart;
			}
			set
			{
				if ((this._AddressPart != value))
				{
					this._AddressPart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(4000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(50)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="NVarChar(50)")]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this._TelHome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelBusiness", DbType="NVarChar(50)")]
		public string TelBusiness
		{
			get
			{
				return this._TelBusiness;
			}
			set
			{
				if ((this._TelBusiness != value))
				{
					this._TelBusiness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile2", DbType="NVarChar(50)")]
		public string Mobile2
		{
			get
			{
				return this._Mobile2;
			}
			set
			{
				if ((this._Mobile2 != value))
				{
					this._Mobile2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo1", DbType="NVarChar(1000)")]
		public string AccountNo1
		{
			get
			{
				return this._AccountNo1;
			}
			set
			{
				if ((this._AccountNo1 != value))
				{
					this._AccountNo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo2", DbType="NVarChar(1000)")]
		public string AccountNo2
		{
			get
			{
				return this._AccountNo2;
			}
			set
			{
				if ((this._AccountNo2 != value))
				{
					this._AccountNo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo3", DbType="NVarChar(1000)")]
		public string AccountNo3
		{
			get
			{
				return this._AccountNo3;
			}
			set
			{
				if ((this._AccountNo3 != value))
				{
					this._AccountNo3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierFamily", DbType="NVarChar(50)")]
		public string CarrierFamily
		{
			get
			{
				return this._CarrierFamily;
			}
			set
			{
				if ((this._CarrierFamily != value))
				{
					this._CarrierFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierNationalCode", DbType="VarChar(10)")]
		public string CarrierNationalCode
		{
			get
			{
				return this._CarrierNationalCode;
			}
			set
			{
				if ((this._CarrierNationalCode != value))
				{
					this._CarrierNationalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierSex", DbType="TinyInt")]
		public System.Nullable<byte> CarrierSex
		{
			get
			{
				return this._CarrierSex;
			}
			set
			{
				if ((this._CarrierSex != value))
				{
					this._CarrierSex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierBrithDate", DbType="VarChar(10)")]
		public string CarrierBrithDate
		{
			get
			{
				return this._CarrierBrithDate;
			}
			set
			{
				if ((this._CarrierBrithDate != value))
				{
					this._CarrierBrithDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierAddress", DbType="NVarChar(1000)")]
		public string CarrierAddress
		{
			get
			{
				return this._CarrierAddress;
			}
			set
			{
				if ((this._CarrierAddress != value))
				{
					this._CarrierAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierTelHome", DbType="VarChar(50)")]
		public string CarrierTelHome
		{
			get
			{
				return this._CarrierTelHome;
			}
			set
			{
				if ((this._CarrierTelHome != value))
				{
					this._CarrierTelHome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierMobile", DbType="VarChar(50)")]
		public string CarrierMobile
		{
			get
			{
				return this._CarrierMobile;
			}
			set
			{
				if ((this._CarrierMobile != value))
				{
					this._CarrierMobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientFillAccount", DbType="Bit")]
		public System.Nullable<bool> PatientFillAccount
		{
			get
			{
				return this._PatientFillAccount;
			}
			set
			{
				if ((this._PatientFillAccount != value))
				{
					this._PatientFillAccount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinShip_Id", DbType="SmallInt")]
		public System.Nullable<short> KinShip_Id
		{
			get
			{
				return this._KinShip_Id;
			}
			set
			{
				if ((this._KinShip_Id != value))
				{
					this._KinShip_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinShipName", DbType="NVarChar(50)")]
		public string KinShipName
		{
			get
			{
				return this._KinShipName;
			}
			set
			{
				if ((this._KinShipName != value))
				{
					this._KinShipName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssueArchive", DbType="NVarChar(50)")]
		public string IssueArchive
		{
			get
			{
				return this._IssueArchive;
			}
			set
			{
				if ((this._IssueArchive != value))
				{
					this._IssueArchive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SingleOrNo", DbType="NVarChar(50)")]
		public string SingleOrNo
		{
			get
			{
				return this._SingleOrNo;
			}
			set
			{
				if ((this._SingleOrNo != value))
				{
					this._SingleOrNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitStatus_Id", DbType="SmallInt")]
		public System.Nullable<short> VisitStatus_Id
		{
			get
			{
				return this._VisitStatus_Id;
			}
			set
			{
				if ((this._VisitStatus_Id != value))
				{
					this._VisitStatus_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitStatusName", DbType="NVarChar(50)")]
		public string VisitStatusName
		{
			get
			{
				return this._VisitStatusName;
			}
			set
			{
				if ((this._VisitStatusName != value))
				{
					this._VisitStatusName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int")]
		public System.Nullable<int> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeDateTime", DbType="VarChar(20)")]
		public string ChangeDateTime
		{
			get
			{
				return this._ChangeDateTime;
			}
			set
			{
				if ((this._ChangeDateTime != value))
				{
					this._ChangeDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersNameFamily", DbType="NVarChar(201)")]
		public string UsersNameFamily
		{
			get
			{
				return this._UsersNameFamily;
			}
			set
			{
				if ((this._UsersNameFamily != value))
				{
					this._UsersNameFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadAddEven", DbType="SmallInt")]
		public System.Nullable<short> BonyadAddEven
		{
			get
			{
				return this._BonyadAddEven;
			}
			set
			{
				if ((this._BonyadAddEven != value))
				{
					this._BonyadAddEven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexStr", DbType="VarChar(3)")]
		public string SexStr
		{
			get
			{
				return this._SexStr;
			}
			set
			{
				if ((this._SexStr != value))
				{
					this._SexStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrNameFamily", DbType="NVarChar(500)")]
		public string MartyrNameFamily
		{
			get
			{
				return this._MartyrNameFamily;
			}
			set
			{
				if ((this._MartyrNameFamily != value))
				{
					this._MartyrNameFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadAddEvenStr", DbType="VarChar(3)")]
		public string BonyadAddEvenStr
		{
			get
			{
				return this._BonyadAddEvenStr;
			}
			set
			{
				if ((this._BonyadAddEvenStr != value))
				{
					this._BonyadAddEvenStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierSexStr", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string CarrierSexStr
		{
			get
			{
				return this._CarrierSexStr;
			}
			set
			{
				if ((this._CarrierSexStr != value))
				{
					this._CarrierSexStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_Id", DbType="SmallInt")]
		public System.Nullable<short> Bank_Id
		{
			get
			{
				return this._Bank_Id;
			}
			set
			{
				if ((this._Bank_Id != value))
				{
					this._Bank_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierBank_Id", DbType="SmallInt")]
		public System.Nullable<short> CarrierBank_Id
		{
			get
			{
				return this._CarrierBank_Id;
			}
			set
			{
				if ((this._CarrierBank_Id != value))
				{
					this._CarrierBank_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarrierBankName", DbType="NVarChar(50)")]
		public string CarrierBankName
		{
			get
			{
				return this._CarrierBankName;
			}
			set
			{
				if ((this._CarrierBankName != value))
				{
					this._CarrierBankName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NVarChar(50)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this._BankName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReciveFileDate", DbType="VarChar(10)")]
		public string ReciveFileDate
		{
			get
			{
				return this._ReciveFileDate;
			}
			set
			{
				if ((this._ReciveFileDate != value))
				{
					this._ReciveFileDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicInsurance", DbType="NVarChar(50)")]
		public string BasicInsurance
		{
			get
			{
				return this._BasicInsurance;
			}
			set
			{
				if ((this._BasicInsurance != value))
				{
					this._BasicInsurance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletionInsurance", DbType="NVarChar(50)")]
		public string CompletionInsurance
		{
			get
			{
				return this._CompletionInsurance;
			}
			set
			{
				if ((this._CompletionInsurance != value))
				{
					this._CompletionInsurance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadDosier", DbType="NVarChar(50)")]
		public string BonyadDosier
		{
			get
			{
				return this._BonyadDosier;
			}
			set
			{
				if ((this._BonyadDosier != value))
				{
					this._BonyadDosier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatePart", DbType="NVarChar(50)")]
		public string StatePart
		{
			get
			{
				return this._StatePart;
			}
			set
			{
				if ((this._StatePart != value))
				{
					this._StatePart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityState", DbType="NVarChar(50)")]
		public string CityState
		{
			get
			{
				return this._CityState;
			}
			set
			{
				if ((this._CityState != value))
				{
					this._CityState = value;
				}
			}
		}
	}
	
	public partial class SP_VisitPatientCareReportResult
	{
		
		private System.Nullable<int> _کد_بیمار;
		
		private string _نام_بیمار;
		
		private string _فامیل_بیمار;
		
		private string _ماه;
		
		private string _کد_ملی;
		
		private string _نام_پدر;
		
		private string _تلفن_محل_کار;
		
		private string _موبایل;
		
		private string _تلفن_منزل;
		
		private System.Nullable<int> _تعداد_کل;
		
		private System.Nullable<int> _تعدا_فرد;
		
		private System.Nullable<int> _تعداد_زوج;
		
		private System.Nullable<int> _تعداد_بدون_عودتی;
		
		private System.Nullable<int> _تعداد_عودتی;
		
		public SP_VisitPatientCareReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بیمار]", Storage="_کد_بیمار", DbType="Int")]
		public System.Nullable<int> کد_بیمار
		{
			get
			{
				return this._کد_بیمار;
			}
			set
			{
				if ((this._کد_بیمار != value))
				{
					this._کد_بیمار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام بیمار]", Storage="_نام_بیمار", DbType="VarChar(50)")]
		public string نام_بیمار
		{
			get
			{
				return this._نام_بیمار;
			}
			set
			{
				if ((this._نام_بیمار != value))
				{
					this._نام_بیمار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[فامیل بیمار]", Storage="_فامیل_بیمار", DbType="VarChar(50)")]
		public string فامیل_بیمار
		{
			get
			{
				return this._فامیل_بیمار;
			}
			set
			{
				if ((this._فامیل_بیمار != value))
				{
					this._فامیل_بیمار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ماه", DbType="VarChar(7)")]
		public string ماه
		{
			get
			{
				return this._ماه;
			}
			set
			{
				if ((this._ماه != value))
				{
					this._ماه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد ملی]", Storage="_کد_ملی", DbType="VarChar(10)")]
		public string کد_ملی
		{
			get
			{
				return this._کد_ملی;
			}
			set
			{
				if ((this._کد_ملی != value))
				{
					this._کد_ملی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[نام پدر]", Storage="_نام_پدر", DbType="VarChar(50)")]
		public string نام_پدر
		{
			get
			{
				return this._نام_پدر;
			}
			set
			{
				if ((this._نام_پدر != value))
				{
					this._نام_پدر = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تلفن محل کار]", Storage="_تلفن_محل_کار", DbType="VarChar(50)")]
		public string تلفن_محل_کار
		{
			get
			{
				return this._تلفن_محل_کار;
			}
			set
			{
				if ((this._تلفن_محل_کار != value))
				{
					this._تلفن_محل_کار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_موبایل", DbType="VarChar(50)")]
		public string موبایل
		{
			get
			{
				return this._موبایل;
			}
			set
			{
				if ((this._موبایل != value))
				{
					this._موبایل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تلفن منزل]", Storage="_تلفن_منزل", DbType="VarChar(50)")]
		public string تلفن_منزل
		{
			get
			{
				return this._تلفن_منزل;
			}
			set
			{
				if ((this._تلفن_منزل != value))
				{
					this._تلفن_منزل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعداد کل]", Storage="_تعداد_کل", DbType="Int")]
		public System.Nullable<int> تعداد_کل
		{
			get
			{
				return this._تعداد_کل;
			}
			set
			{
				if ((this._تعداد_کل != value))
				{
					this._تعداد_کل = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعدا فرد]", Storage="_تعدا_فرد", DbType="Int")]
		public System.Nullable<int> تعدا_فرد
		{
			get
			{
				return this._تعدا_فرد;
			}
			set
			{
				if ((this._تعدا_فرد != value))
				{
					this._تعدا_فرد = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعداد زوج]", Storage="_تعداد_زوج", DbType="Int")]
		public System.Nullable<int> تعداد_زوج
		{
			get
			{
				return this._تعداد_زوج;
			}
			set
			{
				if ((this._تعداد_زوج != value))
				{
					this._تعداد_زوج = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعداد بدون عودتی]", Storage="_تعداد_بدون_عودتی", DbType="Int")]
		public System.Nullable<int> تعداد_بدون_عودتی
		{
			get
			{
				return this._تعداد_بدون_عودتی;
			}
			set
			{
				if ((this._تعداد_بدون_عودتی != value))
				{
					this._تعداد_بدون_عودتی = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعداد عودتی]", Storage="_تعداد_عودتی", DbType="Int")]
		public System.Nullable<int> تعداد_عودتی
		{
			get
			{
				return this._تعداد_عودتی;
			}
			set
			{
				if ((this._تعداد_عودتی != value))
				{
					this._تعداد_عودتی = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
