#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKH.Contacts.Model.PersonTelMob
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhysiotherapyCare")]
	public partial class DataClassesPersonTelMobDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_PersonTelMob(TBL_PersonTelMob instance);
    partial void UpdateTBL_PersonTelMob(TBL_PersonTelMob instance);
    partial void DeleteTBL_PersonTelMob(TBL_PersonTelMob instance);
    #endregion
		
		public DataClassesPersonTelMobDataContext() : 
				base(global::MKH.Contacts.Model.Properties.Settings.Default.PhysiotherapyCareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPersonTelMobDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPersonTelMobDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPersonTelMobDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPersonTelMobDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_PersonTelMob> VW_PersonTelMobs
		{
			get
			{
				return this.GetTable<VW_PersonTelMob>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PersonTelMob> TBL_PersonTelMobs
		{
			get
			{
				return this.GetTable<TBL_PersonTelMob>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="TEL.SP_PersonTelMobDelete")]
		public int SP_PersonTelMobDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="TEL.SP_PersonTelMobInsert")]
		public int SP_PersonTelMobInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] ref System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonPic", DbType="VarBinary(MAX)")] System.Data.Linq.Binary personPic, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentName", DbType="NVarChar(50)")] string parentName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNO", DbType="VarChar(10)")] string iDNO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode", DbType="VarChar(10)")] string nationalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate", DbType="VarChar(10)")] string brithDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithCityName", DbType="NVarChar(50)")] string brithCityName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelHome", DbType="VarChar(50)")] string telHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelBusiness", DbType="VarChar(50)")] string telBusiness, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="VarChar(50)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile2", DbType="VarChar(50)")] string mobile2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(2000)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressBusiness", DbType="NVarChar(2000)")] string addressBusiness, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(2000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, firstName, lastName, personPic, parentName, iDNO, nationalCode, brithDate, brithCityName, telHome, telBusiness, mobile, mobile2, email, address, addressBusiness, description, active, msgRet);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(18)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="TEL.SP_PersonTelMobUpdate")]
		public int SP_PersonTelMobUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonPic", DbType="VarBinary(MAX)")] System.Data.Linq.Binary personPic, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentName", DbType="NVarChar(50)")] string parentName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNO", DbType="VarChar(10)")] string iDNO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode", DbType="VarChar(10)")] string nationalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate", DbType="VarChar(10)")] string brithDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithCityName", DbType="NVarChar(50)")] string brithCityName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelHome", DbType="VarChar(50)")] string telHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelBusiness", DbType="VarChar(50)")] string telBusiness, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="VarChar(50)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile2", DbType="VarChar(50)")] string mobile2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(2000)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressBusiness", DbType="NVarChar(2000)")] string addressBusiness, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(2000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, firstName, lastName, personPic, parentName, iDNO, nationalCode, brithDate, brithCityName, telHome, telBusiness, mobile, mobile2, email, address, addressBusiness, description, active, msgRet);
			msgRet = ((string)(result.GetParameterValue(18)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="TEL.SP_PersonTelMobSelectWithGroupPerson")]
		public ISingleResult<VW_PersonTelMob> SP_PersonTelMobSelectWithGroupPerson([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Group_ID", DbType="Int")] System.Nullable<int> group_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), group_ID, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((ISingleResult<VW_PersonTelMob>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="TEL.VW_PersonTelMob")]
	public partial class VW_PersonTelMob
	{
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private byte[] _PersonPic;
		
		private string _ParentName;
		
		private string _IDNO;
		
		private string _NationalCode;
		
		private string _BrithDate;
		
		private string _BrithCityName;
		
		private string _TelHome;
		
		private string _TelBusiness;
		
		private string _Mobile;
		
		private string _Mobile2;
		
		private string _Email;
		
		private string _Address;
		
		private string _AddressBusiness;
		
		private string _Description;
		
		private System.Nullable<bool> _Active;
		
		private string _GroupName;
		
		public VW_PersonTelMob()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonPic", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public byte[] PersonPic
		{
			get
			{
				return this._PersonPic;
			}
			set
			{
				if ((this._PersonPic != value))
				{
					this._PersonPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentName", DbType="NVarChar(50)")]
		public string ParentName
		{
			get
			{
				return this._ParentName;
			}
			set
			{
				if ((this._ParentName != value))
				{
					this._ParentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="VarChar(10)")]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this._IDNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode", DbType="VarChar(10)")]
		public string NationalCode
		{
			get
			{
				return this._NationalCode;
			}
			set
			{
				if ((this._NationalCode != value))
				{
					this._NationalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate", DbType="VarChar(10)")]
		public string BrithDate
		{
			get
			{
				return this._BrithDate;
			}
			set
			{
				if ((this._BrithDate != value))
				{
					this._BrithDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithCityName", DbType="NVarChar(50)")]
		public string BrithCityName
		{
			get
			{
				return this._BrithCityName;
			}
			set
			{
				if ((this._BrithCityName != value))
				{
					this._BrithCityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="VarChar(50)")]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this._TelHome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelBusiness", DbType="VarChar(50)")]
		public string TelBusiness
		{
			get
			{
				return this._TelBusiness;
			}
			set
			{
				if ((this._TelBusiness != value))
				{
					this._TelBusiness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile2", DbType="VarChar(50)")]
		public string Mobile2
		{
			get
			{
				return this._Mobile2;
			}
			set
			{
				if ((this._Mobile2 != value))
				{
					this._Mobile2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(2000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressBusiness", DbType="NVarChar(2000)")]
		public string AddressBusiness
		{
			get
			{
				return this._AddressBusiness;
			}
			set
			{
				if ((this._AddressBusiness != value))
				{
					this._AddressBusiness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(2000)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="TEL.TBL_PersonTelMob")]
	public partial class TBL_PersonTelMob : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private byte[] _PersonPic;
		
		private string _ParentName;
		
		private string _IDNO;
		
		private string _NationalCode;
		
		private string _BrithDate;
		
		private string _BrithCityName;
		
		private string _TelHome;
		
		private string _TelBusiness;
		
		private string _Mobile;
		
		private string _Mobile2;
		
		private string _Email;
		
		private string _Address;
		
		private string _AddressBusiness;
		
		private string _Description;
		
		private System.Nullable<bool> _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnPersonPicChanging(byte[] value);
    partial void OnPersonPicChanged();
    partial void OnParentNameChanging(string value);
    partial void OnParentNameChanged();
    partial void OnIDNOChanging(string value);
    partial void OnIDNOChanged();
    partial void OnNationalCodeChanging(string value);
    partial void OnNationalCodeChanged();
    partial void OnBrithDateChanging(string value);
    partial void OnBrithDateChanged();
    partial void OnBrithCityNameChanging(string value);
    partial void OnBrithCityNameChanged();
    partial void OnTelHomeChanging(string value);
    partial void OnTelHomeChanged();
    partial void OnTelBusinessChanging(string value);
    partial void OnTelBusinessChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnMobile2Changing(string value);
    partial void OnMobile2Changed();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddressBusinessChanging(string value);
    partial void OnAddressBusinessChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public TBL_PersonTelMob()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonPic", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public byte[] PersonPic
		{
			get
			{
				return this._PersonPic;
			}
			set
			{
				if ((this._PersonPic != value))
				{
					this.OnPersonPicChanging(value);
					this.SendPropertyChanging();
					this._PersonPic = value;
					this.SendPropertyChanged("PersonPic");
					this.OnPersonPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentName", DbType="NVarChar(50)")]
		public string ParentName
		{
			get
			{
				return this._ParentName;
			}
			set
			{
				if ((this._ParentName != value))
				{
					this.OnParentNameChanging(value);
					this.SendPropertyChanging();
					this._ParentName = value;
					this.SendPropertyChanged("ParentName");
					this.OnParentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="VarChar(10)")]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this.OnIDNOChanging(value);
					this.SendPropertyChanging();
					this._IDNO = value;
					this.SendPropertyChanged("IDNO");
					this.OnIDNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode", DbType="VarChar(10)")]
		public string NationalCode
		{
			get
			{
				return this._NationalCode;
			}
			set
			{
				if ((this._NationalCode != value))
				{
					this.OnNationalCodeChanging(value);
					this.SendPropertyChanging();
					this._NationalCode = value;
					this.SendPropertyChanged("NationalCode");
					this.OnNationalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate", DbType="VarChar(10)")]
		public string BrithDate
		{
			get
			{
				return this._BrithDate;
			}
			set
			{
				if ((this._BrithDate != value))
				{
					this.OnBrithDateChanging(value);
					this.SendPropertyChanging();
					this._BrithDate = value;
					this.SendPropertyChanged("BrithDate");
					this.OnBrithDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithCityName", DbType="NVarChar(50)")]
		public string BrithCityName
		{
			get
			{
				return this._BrithCityName;
			}
			set
			{
				if ((this._BrithCityName != value))
				{
					this.OnBrithCityNameChanging(value);
					this.SendPropertyChanging();
					this._BrithCityName = value;
					this.SendPropertyChanged("BrithCityName");
					this.OnBrithCityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="VarChar(50)")]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this.OnTelHomeChanging(value);
					this.SendPropertyChanging();
					this._TelHome = value;
					this.SendPropertyChanged("TelHome");
					this.OnTelHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelBusiness", DbType="VarChar(50)")]
		public string TelBusiness
		{
			get
			{
				return this._TelBusiness;
			}
			set
			{
				if ((this._TelBusiness != value))
				{
					this.OnTelBusinessChanging(value);
					this.SendPropertyChanging();
					this._TelBusiness = value;
					this.SendPropertyChanged("TelBusiness");
					this.OnTelBusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile2", DbType="VarChar(50)")]
		public string Mobile2
		{
			get
			{
				return this._Mobile2;
			}
			set
			{
				if ((this._Mobile2 != value))
				{
					this.OnMobile2Changing(value);
					this.SendPropertyChanging();
					this._Mobile2 = value;
					this.SendPropertyChanged("Mobile2");
					this.OnMobile2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(2000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressBusiness", DbType="NVarChar(2000)")]
		public string AddressBusiness
		{
			get
			{
				return this._AddressBusiness;
			}
			set
			{
				if ((this._AddressBusiness != value))
				{
					this.OnAddressBusinessChanging(value);
					this.SendPropertyChanging();
					this._AddressBusiness = value;
					this.SendPropertyChanged("AddressBusiness");
					this.OnAddressBusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
