#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysiotherapyCare.Model.VisitPatient
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhysiotherapyCare")]
	public partial class DataClassesVisitPatientLinkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_VaccinationVisitPatient(TBL_VaccinationVisitPatient instance);
    partial void UpdateTBL_VaccinationVisitPatient(TBL_VaccinationVisitPatient instance);
    partial void DeleteTBL_VaccinationVisitPatient(TBL_VaccinationVisitPatient instance);
    partial void InsertTBL_SicknessVisitPatient(TBL_SicknessVisitPatient instance);
    partial void UpdateTBL_SicknessVisitPatient(TBL_SicknessVisitPatient instance);
    partial void DeleteTBL_SicknessVisitPatient(TBL_SicknessVisitPatient instance);
    partial void InsertTBL_ParaclinicVisitPatient(TBL_ParaclinicVisitPatient instance);
    partial void UpdateTBL_ParaclinicVisitPatient(TBL_ParaclinicVisitPatient instance);
    partial void DeleteTBL_ParaclinicVisitPatient(TBL_ParaclinicVisitPatient instance);
    partial void InsertTBL_EquipmentUseVisitPatient(TBL_EquipmentUseVisitPatient instance);
    partial void UpdateTBL_EquipmentUseVisitPatient(TBL_EquipmentUseVisitPatient instance);
    partial void DeleteTBL_EquipmentUseVisitPatient(TBL_EquipmentUseVisitPatient instance);
    partial void InsertTBL_DrugVisitPatient(TBL_DrugVisitPatient instance);
    partial void UpdateTBL_DrugVisitPatient(TBL_DrugVisitPatient instance);
    partial void DeleteTBL_DrugVisitPatient(TBL_DrugVisitPatient instance);
    partial void InsertTBL_BedsoreVisitPatient(TBL_BedsoreVisitPatient instance);
    partial void UpdateTBL_BedsoreVisitPatient(TBL_BedsoreVisitPatient instance);
    partial void DeleteTBL_BedsoreVisitPatient(TBL_BedsoreVisitPatient instance);
    #endregion
		
		public DataClassesVisitPatientLinkDataContext() : 
				base(global::PhysiotherapyCare.Model.Properties.Settings.Default.PhysiotherapyCareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientLinkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientLinkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientLinkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitPatientLinkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_VaccinationVisitPatient> TBL_VaccinationVisitPatients
		{
			get
			{
				return this.GetTable<TBL_VaccinationVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<TBL_SicknessVisitPatient> TBL_SicknessVisitPatients
		{
			get
			{
				return this.GetTable<TBL_SicknessVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ParaclinicVisitPatient> TBL_ParaclinicVisitPatients
		{
			get
			{
				return this.GetTable<TBL_ParaclinicVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<TBL_EquipmentUseVisitPatient> TBL_EquipmentUseVisitPatients
		{
			get
			{
				return this.GetTable<TBL_EquipmentUseVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DrugVisitPatient> TBL_DrugVisitPatients
		{
			get
			{
				return this.GetTable<TBL_DrugVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<TBL_BedsoreVisitPatient> TBL_BedsoreVisitPatients
		{
			get
			{
				return this.GetTable<TBL_BedsoreVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<VW_SicknessVisitPatient> VW_SicknessVisitPatients
		{
			get
			{
				return this.GetTable<VW_SicknessVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<VW_ParaclinicVisitPatient> VW_ParaclinicVisitPatients
		{
			get
			{
				return this.GetTable<VW_ParaclinicVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<VW_EquipmentUseVisitPatient> VW_EquipmentUseVisitPatients
		{
			get
			{
				return this.GetTable<VW_EquipmentUseVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<VW_DrugVisitPatient> VW_DrugVisitPatients
		{
			get
			{
				return this.GetTable<VW_DrugVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<VW_BedsoreVisitPatient> VW_BedsoreVisitPatients
		{
			get
			{
				return this.GetTable<VW_BedsoreVisitPatient>();
			}
		}
		
		public System.Data.Linq.Table<VW_VaccinationVisitPatient> VW_VaccinationVisitPatients
		{
			get
			{
				return this.GetTable<VW_VaccinationVisitPatient>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_BedsoreVisitPatientDelete")]
		public int SP_BedsoreVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_DrugVisitPatientDelete")]
		public int SP_DrugVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_EquipmentUseVisitPatientDelete")]
		public int SP_EquipmentUseVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_ParaclinicVisitPatientDelete")]
		public int SP_ParaclinicVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_SicknessVisitPatientDelete")]
		public int SP_SicknessVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VaccinationVisitPatientDelete")]
		public int SP_VaccinationVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VisitPatientWithDrugVisitPatientDelete")]
		public int SP_VisitPatientWithDrugVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitPatient_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VisitPatientWithEquipmentUseVisitPatientDelete")]
		public int SP_VisitPatientWithEquipmentUseVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitPatient_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VisitPatientWithSicknessVisitPatientDelete")]
		public int SP_VisitPatientWithSicknessVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitPatient_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VisitPatientWithVaccinationVisitPatientDelete")]
		public int SP_VisitPatientWithVaccinationVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitPatient_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VisitPatientWithBedsoreVisitPatientDelete")]
		public int SP_VisitPatientWithBedsoreVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitPatient_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VisitPatientWithParaclinicVisitPatientDelete")]
		public int SP_VisitPatientWithParaclinicVisitPatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitPatient_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VaccinationVisitPatientInsert")]
		public int SP_VaccinationVisitPatientInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] ref System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vaccination_Id", DbType="Int")] System.Nullable<int> vaccination_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Few", DbType="Int")] System.Nullable<int> few, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, vaccination_Id, few, description, msgRet);
			id = ((System.Nullable<long>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_VaccinationVisitPatientUpdate")]
		public int SP_VaccinationVisitPatientUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vaccination_Id", DbType="Int")] System.Nullable<int> vaccination_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Few", DbType="Int")] System.Nullable<int> few, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, vaccination_Id, few, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_SicknessVisitPatientUpdate")]
		public int SP_SicknessVisitPatientUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SicknessDetail_Id", DbType="Int")] System.Nullable<int> sicknessDetail_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, sicknessDetail_Id, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_SicknessVisitPatientInsert")]
		public int SP_SicknessVisitPatientInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] ref System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SicknessDetail_Id", DbType="Int")] System.Nullable<int> sicknessDetail_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, sicknessDetail_Id, description, msgRet);
			id = ((System.Nullable<long>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_ParaclinicVisitPatientUpdate")]
		public int SP_ParaclinicVisitPatientUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Paraclinic_Id", DbType="Int")] System.Nullable<int> paraclinic_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParaclinicsState", DbType="NVarChar(100)")] string paraclinicsState, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, paraclinic_Id, paraclinicsState, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_ParaclinicVisitPatientInsert")]
		public int SP_ParaclinicVisitPatientInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] ref System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Paraclinic_Id", DbType="Int")] System.Nullable<int> paraclinic_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParaclinicsState", DbType="NVarChar(100)")] string paraclinicsState, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, paraclinic_Id, paraclinicsState, description, msgRet);
			id = ((System.Nullable<long>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_EquipmentUseVisitPatientUpdate")]
		public int SP_EquipmentUseVisitPatientUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EquipmentUse_Id", DbType="Int")] System.Nullable<int> equipmentUse_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Few", DbType="Int")] System.Nullable<int> few, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, equipmentUse_Id, few, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_EquipmentUseVisitPatientInsert")]
		public int SP_EquipmentUseVisitPatientInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] ref System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EquipmentUse_Id", DbType="Int")] System.Nullable<int> equipmentUse_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Few", DbType="Int")] System.Nullable<int> few, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, equipmentUse_Id, few, description, msgRet);
			id = ((System.Nullable<long>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_BedsoreVisitPatientUpdate")]
		public int SP_BedsoreVisitPatientUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsorePosition", DbType="NVarChar(500)")] string bedsorePosition, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreMeasurement", DbType="Int")] System.Nullable<int> bedsoreMeasurement, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreDeep", DbType="NVarChar(500)")] string bedsoreDeep, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreStartTime", DbType="NVarChar(500)")] string bedsoreStartTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreGrade", DbType="NVarChar(500)")] string bedsoreGrade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreRemain", DbType="NVarChar(500)")] string bedsoreRemain, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, bedsorePosition, bedsoreMeasurement, bedsoreDeep, bedsoreStartTime, bedsoreGrade, bedsoreRemain, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_BedsoreVisitPatientInsert")]
		public int SP_BedsoreVisitPatientInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] ref System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsorePosition", DbType="NVarChar(500)")] string bedsorePosition, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreMeasurement", DbType="Int")] System.Nullable<int> bedsoreMeasurement, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreDeep", DbType="NVarChar(500)")] string bedsoreDeep, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreStartTime", DbType="NVarChar(500)")] string bedsoreStartTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreGrade", DbType="NVarChar(500)")] string bedsoreGrade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedsoreRemain", DbType="NVarChar(500)")] string bedsoreRemain, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, bedsorePosition, bedsoreMeasurement, bedsoreDeep, bedsoreStartTime, bedsoreGrade, bedsoreRemain, description, msgRet);
			id = ((System.Nullable<long>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_DrugVisitPatientUpdate")]
		public int SP_DrugVisitPatientUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Drug_Id", DbType="Int")] System.Nullable<int> drug_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseAmount", DbType="NVarChar(500)")] string useAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, drug_Id, useAmount, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="VST.SP_DrugVisitPatientInsert")]
		public int SP_DrugVisitPatientInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] ref System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitPatient_Id", DbType="BigInt")] System.Nullable<long> visitPatient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Drug_Id", DbType="Int")] System.Nullable<int> drug_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UseAmount", DbType="NVarChar(500)")] string useAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, visitPatient_Id, drug_Id, useAmount, description, msgRet);
			id = ((System.Nullable<long>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.TBL_VaccinationVisitPatient")]
	public partial class TBL_VaccinationVisitPatient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _Vaccination_Id;
		
		private System.Nullable<int> _Few;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnVisitPatient_IdChanging(System.Nullable<long> value);
    partial void OnVisitPatient_IdChanged();
    partial void OnVaccination_IdChanging(System.Nullable<int> value);
    partial void OnVaccination_IdChanged();
    partial void OnFewChanging(System.Nullable<int> value);
    partial void OnFewChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_VaccinationVisitPatient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this.OnVisitPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitPatient_Id = value;
					this.SendPropertyChanged("VisitPatient_Id");
					this.OnVisitPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vaccination_Id", DbType="Int")]
		public System.Nullable<int> Vaccination_Id
		{
			get
			{
				return this._Vaccination_Id;
			}
			set
			{
				if ((this._Vaccination_Id != value))
				{
					this.OnVaccination_IdChanging(value);
					this.SendPropertyChanging();
					this._Vaccination_Id = value;
					this.SendPropertyChanged("Vaccination_Id");
					this.OnVaccination_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Few", DbType="Int")]
		public System.Nullable<int> Few
		{
			get
			{
				return this._Few;
			}
			set
			{
				if ((this._Few != value))
				{
					this.OnFewChanging(value);
					this.SendPropertyChanging();
					this._Few = value;
					this.SendPropertyChanged("Few");
					this.OnFewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.TBL_SicknessVisitPatient")]
	public partial class TBL_SicknessVisitPatient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _SicknessDetail_Id;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnVisitPatient_IdChanging(System.Nullable<long> value);
    partial void OnVisitPatient_IdChanged();
    partial void OnSicknessDetail_IdChanging(System.Nullable<int> value);
    partial void OnSicknessDetail_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_SicknessVisitPatient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this.OnVisitPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitPatient_Id = value;
					this.SendPropertyChanged("VisitPatient_Id");
					this.OnVisitPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SicknessDetail_Id", DbType="Int")]
		public System.Nullable<int> SicknessDetail_Id
		{
			get
			{
				return this._SicknessDetail_Id;
			}
			set
			{
				if ((this._SicknessDetail_Id != value))
				{
					this.OnSicknessDetail_IdChanging(value);
					this.SendPropertyChanging();
					this._SicknessDetail_Id = value;
					this.SendPropertyChanged("SicknessDetail_Id");
					this.OnSicknessDetail_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.TBL_ParaclinicVisitPatient")]
	public partial class TBL_ParaclinicVisitPatient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _Paraclinic_Id;
		
		private string _ParaclinicsState;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnVisitPatient_IdChanging(System.Nullable<long> value);
    partial void OnVisitPatient_IdChanged();
    partial void OnParaclinic_IdChanging(System.Nullable<int> value);
    partial void OnParaclinic_IdChanged();
    partial void OnParaclinicsStateChanging(string value);
    partial void OnParaclinicsStateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_ParaclinicVisitPatient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this.OnVisitPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitPatient_Id = value;
					this.SendPropertyChanged("VisitPatient_Id");
					this.OnVisitPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paraclinic_Id", DbType="Int")]
		public System.Nullable<int> Paraclinic_Id
		{
			get
			{
				return this._Paraclinic_Id;
			}
			set
			{
				if ((this._Paraclinic_Id != value))
				{
					this.OnParaclinic_IdChanging(value);
					this.SendPropertyChanging();
					this._Paraclinic_Id = value;
					this.SendPropertyChanged("Paraclinic_Id");
					this.OnParaclinic_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParaclinicsState", DbType="NVarChar(100)")]
		public string ParaclinicsState
		{
			get
			{
				return this._ParaclinicsState;
			}
			set
			{
				if ((this._ParaclinicsState != value))
				{
					this.OnParaclinicsStateChanging(value);
					this.SendPropertyChanging();
					this._ParaclinicsState = value;
					this.SendPropertyChanged("ParaclinicsState");
					this.OnParaclinicsStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.TBL_EquipmentUseVisitPatient")]
	public partial class TBL_EquipmentUseVisitPatient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _EquipmentUse_Id;
		
		private System.Nullable<int> _Few;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnVisitPatient_IdChanging(System.Nullable<long> value);
    partial void OnVisitPatient_IdChanged();
    partial void OnEquipmentUse_IdChanging(System.Nullable<int> value);
    partial void OnEquipmentUse_IdChanged();
    partial void OnFewChanging(System.Nullable<int> value);
    partial void OnFewChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_EquipmentUseVisitPatient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this.OnVisitPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitPatient_Id = value;
					this.SendPropertyChanged("VisitPatient_Id");
					this.OnVisitPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentUse_Id", DbType="Int")]
		public System.Nullable<int> EquipmentUse_Id
		{
			get
			{
				return this._EquipmentUse_Id;
			}
			set
			{
				if ((this._EquipmentUse_Id != value))
				{
					this.OnEquipmentUse_IdChanging(value);
					this.SendPropertyChanging();
					this._EquipmentUse_Id = value;
					this.SendPropertyChanged("EquipmentUse_Id");
					this.OnEquipmentUse_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Few", DbType="Int")]
		public System.Nullable<int> Few
		{
			get
			{
				return this._Few;
			}
			set
			{
				if ((this._Few != value))
				{
					this.OnFewChanging(value);
					this.SendPropertyChanging();
					this._Few = value;
					this.SendPropertyChanged("Few");
					this.OnFewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.TBL_DrugVisitPatient")]
	public partial class TBL_DrugVisitPatient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _Drug_Id;
		
		private string _UseAmount;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnVisitPatient_IdChanging(System.Nullable<long> value);
    partial void OnVisitPatient_IdChanged();
    partial void OnDrug_IdChanging(System.Nullable<int> value);
    partial void OnDrug_IdChanged();
    partial void OnUseAmountChanging(string value);
    partial void OnUseAmountChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_DrugVisitPatient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this.OnVisitPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitPatient_Id = value;
					this.SendPropertyChanged("VisitPatient_Id");
					this.OnVisitPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Drug_Id", DbType="Int")]
		public System.Nullable<int> Drug_Id
		{
			get
			{
				return this._Drug_Id;
			}
			set
			{
				if ((this._Drug_Id != value))
				{
					this.OnDrug_IdChanging(value);
					this.SendPropertyChanging();
					this._Drug_Id = value;
					this.SendPropertyChanged("Drug_Id");
					this.OnDrug_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseAmount", DbType="NVarChar(500)")]
		public string UseAmount
		{
			get
			{
				return this._UseAmount;
			}
			set
			{
				if ((this._UseAmount != value))
				{
					this.OnUseAmountChanging(value);
					this.SendPropertyChanging();
					this._UseAmount = value;
					this.SendPropertyChanged("UseAmount");
					this.OnUseAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.TBL_BedsoreVisitPatient")]
	public partial class TBL_BedsoreVisitPatient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private string _BedsorePosition;
		
		private System.Nullable<int> _BedsoreMeasurement;
		
		private string _BedsoreDeep;
		
		private string _BedsoreStartTime;
		
		private string _BedsoreGrade;
		
		private string _BedsoreRemain;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnVisitPatient_IdChanging(System.Nullable<long> value);
    partial void OnVisitPatient_IdChanged();
    partial void OnBedsorePositionChanging(string value);
    partial void OnBedsorePositionChanged();
    partial void OnBedsoreMeasurementChanging(System.Nullable<int> value);
    partial void OnBedsoreMeasurementChanged();
    partial void OnBedsoreDeepChanging(string value);
    partial void OnBedsoreDeepChanged();
    partial void OnBedsoreStartTimeChanging(string value);
    partial void OnBedsoreStartTimeChanged();
    partial void OnBedsoreGradeChanging(string value);
    partial void OnBedsoreGradeChanged();
    partial void OnBedsoreRemainChanging(string value);
    partial void OnBedsoreRemainChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_BedsoreVisitPatient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this.OnVisitPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitPatient_Id = value;
					this.SendPropertyChanged("VisitPatient_Id");
					this.OnVisitPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsorePosition", DbType="NVarChar(500)")]
		public string BedsorePosition
		{
			get
			{
				return this._BedsorePosition;
			}
			set
			{
				if ((this._BedsorePosition != value))
				{
					this.OnBedsorePositionChanging(value);
					this.SendPropertyChanging();
					this._BedsorePosition = value;
					this.SendPropertyChanged("BedsorePosition");
					this.OnBedsorePositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreMeasurement", DbType="Int")]
		public System.Nullable<int> BedsoreMeasurement
		{
			get
			{
				return this._BedsoreMeasurement;
			}
			set
			{
				if ((this._BedsoreMeasurement != value))
				{
					this.OnBedsoreMeasurementChanging(value);
					this.SendPropertyChanging();
					this._BedsoreMeasurement = value;
					this.SendPropertyChanged("BedsoreMeasurement");
					this.OnBedsoreMeasurementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreDeep", DbType="NVarChar(500)")]
		public string BedsoreDeep
		{
			get
			{
				return this._BedsoreDeep;
			}
			set
			{
				if ((this._BedsoreDeep != value))
				{
					this.OnBedsoreDeepChanging(value);
					this.SendPropertyChanging();
					this._BedsoreDeep = value;
					this.SendPropertyChanged("BedsoreDeep");
					this.OnBedsoreDeepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreStartTime", DbType="NVarChar(500)")]
		public string BedsoreStartTime
		{
			get
			{
				return this._BedsoreStartTime;
			}
			set
			{
				if ((this._BedsoreStartTime != value))
				{
					this.OnBedsoreStartTimeChanging(value);
					this.SendPropertyChanging();
					this._BedsoreStartTime = value;
					this.SendPropertyChanged("BedsoreStartTime");
					this.OnBedsoreStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreGrade", DbType="NVarChar(500)")]
		public string BedsoreGrade
		{
			get
			{
				return this._BedsoreGrade;
			}
			set
			{
				if ((this._BedsoreGrade != value))
				{
					this.OnBedsoreGradeChanging(value);
					this.SendPropertyChanging();
					this._BedsoreGrade = value;
					this.SendPropertyChanged("BedsoreGrade");
					this.OnBedsoreGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreRemain", DbType="NVarChar(500)")]
		public string BedsoreRemain
		{
			get
			{
				return this._BedsoreRemain;
			}
			set
			{
				if ((this._BedsoreRemain != value))
				{
					this.OnBedsoreRemainChanging(value);
					this.SendPropertyChanging();
					this._BedsoreRemain = value;
					this.SendPropertyChanged("BedsoreRemain");
					this.OnBedsoreRemainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.VW_SicknessVisitPatient")]
	public partial class VW_SicknessVisitPatient
	{
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _SicknessDetail_Id;
		
		private string _Description;
		
		private System.Nullable<int> _Sickness_Id;
		
		private string _SicknessDetailName;
		
		private string _SicknessName;
		
		public VW_SicknessVisitPatient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this._VisitPatient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SicknessDetail_Id", DbType="Int")]
		public System.Nullable<int> SicknessDetail_Id
		{
			get
			{
				return this._SicknessDetail_Id;
			}
			set
			{
				if ((this._SicknessDetail_Id != value))
				{
					this._SicknessDetail_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sickness_Id", DbType="Int")]
		public System.Nullable<int> Sickness_Id
		{
			get
			{
				return this._Sickness_Id;
			}
			set
			{
				if ((this._Sickness_Id != value))
				{
					this._Sickness_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SicknessDetailName", DbType="NVarChar(100)")]
		public string SicknessDetailName
		{
			get
			{
				return this._SicknessDetailName;
			}
			set
			{
				if ((this._SicknessDetailName != value))
				{
					this._SicknessDetailName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SicknessName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SicknessName
		{
			get
			{
				return this._SicknessName;
			}
			set
			{
				if ((this._SicknessName != value))
				{
					this._SicknessName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.VW_ParaclinicVisitPatient")]
	public partial class VW_ParaclinicVisitPatient
	{
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _Paraclinic_Id;
		
		private string _ParaclinicsState;
		
		private string _Description;
		
		private string _ParaclinicName;
		
		public VW_ParaclinicVisitPatient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this._VisitPatient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paraclinic_Id", DbType="Int")]
		public System.Nullable<int> Paraclinic_Id
		{
			get
			{
				return this._Paraclinic_Id;
			}
			set
			{
				if ((this._Paraclinic_Id != value))
				{
					this._Paraclinic_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParaclinicsState", DbType="NVarChar(100)")]
		public string ParaclinicsState
		{
			get
			{
				return this._ParaclinicsState;
			}
			set
			{
				if ((this._ParaclinicsState != value))
				{
					this._ParaclinicsState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParaclinicName", DbType="NVarChar(50)")]
		public string ParaclinicName
		{
			get
			{
				return this._ParaclinicName;
			}
			set
			{
				if ((this._ParaclinicName != value))
				{
					this._ParaclinicName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.VW_EquipmentUseVisitPatient")]
	public partial class VW_EquipmentUseVisitPatient
	{
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _EquipmentUse_Id;
		
		private System.Nullable<int> _Few;
		
		private string _Description;
		
		private string _EquipmentUseName;
		
		public VW_EquipmentUseVisitPatient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this._VisitPatient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentUse_Id", DbType="Int")]
		public System.Nullable<int> EquipmentUse_Id
		{
			get
			{
				return this._EquipmentUse_Id;
			}
			set
			{
				if ((this._EquipmentUse_Id != value))
				{
					this._EquipmentUse_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Few", DbType="Int")]
		public System.Nullable<int> Few
		{
			get
			{
				return this._Few;
			}
			set
			{
				if ((this._Few != value))
				{
					this._Few = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquipmentUseName", DbType="NVarChar(50)")]
		public string EquipmentUseName
		{
			get
			{
				return this._EquipmentUseName;
			}
			set
			{
				if ((this._EquipmentUseName != value))
				{
					this._EquipmentUseName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.VW_DrugVisitPatient")]
	public partial class VW_DrugVisitPatient
	{
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _Drug_Id;
		
		private string _UseAmount;
		
		private string _Description;
		
		private string _DrugName;
		
		public VW_DrugVisitPatient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this._VisitPatient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Drug_Id", DbType="Int")]
		public System.Nullable<int> Drug_Id
		{
			get
			{
				return this._Drug_Id;
			}
			set
			{
				if ((this._Drug_Id != value))
				{
					this._Drug_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseAmount", DbType="NVarChar(500)")]
		public string UseAmount
		{
			get
			{
				return this._UseAmount;
			}
			set
			{
				if ((this._UseAmount != value))
				{
					this._UseAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugName", DbType="NVarChar(50)")]
		public string DrugName
		{
			get
			{
				return this._DrugName;
			}
			set
			{
				if ((this._DrugName != value))
				{
					this._DrugName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.VW_BedsoreVisitPatient")]
	public partial class VW_BedsoreVisitPatient
	{
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private string _BedsorePosition;
		
		private System.Nullable<int> _BedsoreMeasurement;
		
		private string _BedsoreDeep;
		
		private string _BedsoreStartTime;
		
		private string _BedsoreGrade;
		
		private string _BedsoreRemain;
		
		private string _Description;
		
		public VW_BedsoreVisitPatient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this._VisitPatient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsorePosition", DbType="NVarChar(500)")]
		public string BedsorePosition
		{
			get
			{
				return this._BedsorePosition;
			}
			set
			{
				if ((this._BedsorePosition != value))
				{
					this._BedsorePosition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreMeasurement", DbType="Int")]
		public System.Nullable<int> BedsoreMeasurement
		{
			get
			{
				return this._BedsoreMeasurement;
			}
			set
			{
				if ((this._BedsoreMeasurement != value))
				{
					this._BedsoreMeasurement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreDeep", DbType="NVarChar(500)")]
		public string BedsoreDeep
		{
			get
			{
				return this._BedsoreDeep;
			}
			set
			{
				if ((this._BedsoreDeep != value))
				{
					this._BedsoreDeep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreStartTime", DbType="NVarChar(500)")]
		public string BedsoreStartTime
		{
			get
			{
				return this._BedsoreStartTime;
			}
			set
			{
				if ((this._BedsoreStartTime != value))
				{
					this._BedsoreStartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreGrade", DbType="NVarChar(500)")]
		public string BedsoreGrade
		{
			get
			{
				return this._BedsoreGrade;
			}
			set
			{
				if ((this._BedsoreGrade != value))
				{
					this._BedsoreGrade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedsoreRemain", DbType="NVarChar(500)")]
		public string BedsoreRemain
		{
			get
			{
				return this._BedsoreRemain;
			}
			set
			{
				if ((this._BedsoreRemain != value))
				{
					this._BedsoreRemain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="VST.VW_VaccinationVisitPatient")]
	public partial class VW_VaccinationVisitPatient
	{
		
		private long _Id;
		
		private System.Nullable<long> _VisitPatient_Id;
		
		private System.Nullable<int> _Vaccination_Id;
		
		private System.Nullable<int> _Few;
		
		private string _Description;
		
		private string _VaccinationName;
		
		public VW_VaccinationVisitPatient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitPatient_Id", DbType="BigInt")]
		public System.Nullable<long> VisitPatient_Id
		{
			get
			{
				return this._VisitPatient_Id;
			}
			set
			{
				if ((this._VisitPatient_Id != value))
				{
					this._VisitPatient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vaccination_Id", DbType="Int")]
		public System.Nullable<int> Vaccination_Id
		{
			get
			{
				return this._Vaccination_Id;
			}
			set
			{
				if ((this._Vaccination_Id != value))
				{
					this._Vaccination_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Few", DbType="Int")]
		public System.Nullable<int> Few
		{
			get
			{
				return this._Few;
			}
			set
			{
				if ((this._Few != value))
				{
					this._Few = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaccinationName", DbType="NVarChar(50)")]
		public string VaccinationName
		{
			get
			{
				return this._VaccinationName;
			}
			set
			{
				if ((this._VaccinationName != value))
				{
					this._VaccinationName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
