<?xml version="1.0" encoding="utf-8"?><Database Name="PhysiotherapyCare" Class="DataClassesReciveSMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=PhysiotherapyCare;Integrated Security=True" SettingsObjectName="MKH.SMS.Model.Properties.Settings" SettingsPropertyName="PhysiotherapyCareConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="SMS.TBL_ReciveSMS" Member="TBL_ReciveSMs">
    <Type Name="TBL_ReciveSM">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MessageID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ReciverNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReciverName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReciverJob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReciveDateTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RecipientNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SMS_Few" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Archive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeDateTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="SMS.VW_ReciveSMS" Member="VW_ReciveSMs">
    <Type Name="VW_ReciveSM">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MessageID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ReciverNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReciverName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReciverJob" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReciveDateTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MessageText" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RecipientNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SMS_Few" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Archive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeDateTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UsersNameFamily" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="SMS.SP_ReciveSMSDelete" Method="SP_ReciveSMSDelete">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(2000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="SMS.SP_ReciveSMSUpdate" Method="SP_ReciveSMSUpdate">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MessageID" Parameter="messageID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ReciverNumber" Parameter="reciverNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ReciverName" Parameter="reciverName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ReciverJob" Parameter="reciverJob" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ReciveDateTime" Parameter="reciveDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="MessageText" Parameter="messageText" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="RecipientNumber" Parameter="recipientNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SMS_Few" Parameter="sMS_Few" Type="System.Int32" DbType="Int" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Archive" Parameter="archive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ChangeDateTime" Parameter="changeDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="SMS.SP_ReciveSMSInsert" Method="SP_ReciveSMSInsert">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="MessageID" Parameter="messageID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ReciverNumber" Parameter="reciverNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ReciverName" Parameter="reciverName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ReciverJob" Parameter="reciverJob" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ReciveDateTime" Parameter="reciveDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="MessageText" Parameter="messageText" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="RecipientNumber" Parameter="recipientNumber" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SMS_Few" Parameter="sMS_Few" Type="System.Int32" DbType="Int" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Archive" Parameter="archive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ChangeDateTime" Parameter="changeDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>