#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysiotherapyCare.Model.Patient
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhysiotherapyCare")]
	public partial class DataClassesPatientDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_PatientStateSickness(TBL_PatientStateSickness instance);
    partial void UpdateTBL_PatientStateSickness(TBL_PatientStateSickness instance);
    partial void DeleteTBL_PatientStateSickness(TBL_PatientStateSickness instance);
    partial void InsertTBL_Patient(TBL_Patient instance);
    partial void UpdateTBL_Patient(TBL_Patient instance);
    partial void DeleteTBL_Patient(TBL_Patient instance);
    #endregion
		
		public DataClassesPatientDataContext() : 
				base(global::PhysiotherapyCare.Model.Properties.Settings.Default.PhysiotherapyCareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPatientDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPatientDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPatientDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesPatientDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_PatientStateSickness> TBL_PatientStateSicknesses
		{
			get
			{
				return this.GetTable<TBL_PatientStateSickness>();
			}
		}
		
		public System.Data.Linq.Table<VW_PatientStateSickness> VW_PatientStateSicknesses
		{
			get
			{
				return this.GetTable<VW_PatientStateSickness>();
			}
		}
		
		public System.Data.Linq.Table<VW_Patient> VW_Patients
		{
			get
			{
				return this.GetTable<VW_Patient>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Patient> TBL_Patients
		{
			get
			{
				return this.GetTable<TBL_Patient>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientInjuryStrUpdate")]
		public int SP_PatientInjuryStrUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientStateSicknessDelete")]
		public int SP_PatientStateSicknessDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Patient_Id", DbType="BigInt")] System.Nullable<long> patient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StateSicknessDetail_Id", DbType="Int")] System.Nullable<int> stateSicknessDetail_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), patient_Id, stateSicknessDetail_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientStateSicknessInsert")]
		public int SP_PatientStateSicknessInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Patient_Id", DbType="BigInt")] System.Nullable<long> patient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StateSicknessDetail_Id", DbType="Int")] System.Nullable<int> stateSicknessDetail_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), patient_Id, stateSicknessDetail_Id, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientStateSicknessUpdate")]
		public int SP_PatientStateSicknessUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Patient_Id", DbType="BigInt")] System.Nullable<long> patient_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StateSicknessDetail_Id", DbType="Int")] System.Nullable<int> stateSicknessDetail_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(500)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), patient_Id, stateSicknessDetail_Id, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientDelete")]
		public int SP_PatientDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientReIndexForAllAction")]
		public int SP_PatientReIndexForAllAction([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), msgRet);
			msgRet = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientInsert")]
		public int SP_PatientInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] ref System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreateDate", DbType="NVarChar(20)")] string createDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo", DbType="NVarChar(100)")] string dosiersNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientName", DbType="NVarChar(50)")] string patientName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientFamily", DbType="NVarChar(50)")] string patientFamily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentName", DbType="NVarChar(50)")] string parentName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sex", DbType="TinyInt")] System.Nullable<byte> sex, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNO", DbType="NVarChar(50)")] string iDNO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode", DbType="NVarChar(10)")] string nationalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Martyr_Id", DbType="Int")] System.Nullable<int> martyr_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientTypeStr", DbType="NVarChar(200)")] string patientTypeStr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InjuryTypeStr", DbType="NVarChar(200)")] string injuryTypeStr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate", DbType="NVarChar(10)")] string brithDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithCityName", DbType="NVarChar(50)")] string brithCityName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PercentState", DbType="SmallInt")] System.Nullable<short> percentState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SingleOrNo", DbType="NVarChar(50)")] string singleOrNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BonyadAddEven", DbType="SmallInt")] System.Nullable<short> bonyadAddEven, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BonyadDosier", DbType="NVarChar(50)")] string bonyadDosier, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatePart", DbType="NVarChar(50)")] string statePart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityState", DbType="NVarChar(50)")] string cityState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityPart", DbType="NVarChar(50)")] string cityPart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstitutePart", DbType="SmallInt")] System.Nullable<short> institutePart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressPart", DbType="SmallInt")] System.Nullable<short> addressPart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(4000)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalCode", DbType="NVarChar(50)")] string postalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelHome", DbType="NVarChar(50)")] string telHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelBusiness", DbType="NVarChar(50)")] string telBusiness, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(50)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile2", DbType="NVarChar(50)")] string mobile2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BasicInsurance", DbType="NVarChar(50)")] string basicInsurance, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompletionInsurance", DbType="NVarChar(50)")] string completionInsurance, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastDoctorVisit_Id", DbType="Int")] System.Nullable<int> lastDoctorVisit_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastVisitDate", DbType="NVarChar(20)")] string lastVisitDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastDoctorPhysiotherapy_Id", DbType="Int")] System.Nullable<int> lastDoctorPhysiotherapy_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastPhysiotherapyDate", DbType="NVarChar(20)")] string lastPhysiotherapyDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastDoctorHealthCare_Id", DbType="Int")] System.Nullable<int> lastDoctorHealthCare_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastHealthCareDate", DbType="NVarChar(20)")] string lastHealthCareDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastVisitPatientCare_Id", DbType="BigInt")] System.Nullable<long> lastVisitPatientCare_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastCareDate", DbType="NVarChar(20)")] string lastCareDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bank_Id", DbType="SmallInt")] System.Nullable<short> bank_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNo1", DbType="NVarChar(1000)")] string accountNo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNo2", DbType="NVarChar(1000)")] string accountNo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNo3", DbType="NVarChar(1000)")] string accountNo3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(1000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeActiveDsc", DbType="NVarChar(200)")] string deActiveDsc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="NVarChar(20)")] string changeDateTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, createDate, dosiersNo, patientName, patientFamily, parentName, sex, iDNO, nationalCode, martyr_Id, patientTypeStr, injuryTypeStr, brithDate, brithCityName, percentState, singleOrNo, bonyadAddEven, bonyadDosier, statePart, cityState, cityPart, institutePart, addressPart, address, postalCode, telHome, telBusiness, mobile, mobile2, email, basicInsurance, completionInsurance, lastDoctorVisit_Id, lastVisitDate, lastDoctorPhysiotherapy_Id, lastPhysiotherapyDate, lastDoctorHealthCare_Id, lastHealthCareDate, lastVisitPatientCare_Id, lastCareDate, bank_Id, accountNo1, accountNo2, accountNo3, description, deActiveDsc, active, user_Id, changeDateTime, msgRet);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(49)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientDelUpdate")]
		public int SP_PatientDelUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActiveOrNo", DbType="Bit")] System.Nullable<bool> activeOrNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeActiveDsc", DbType="NVarChar(200)")] string deActiveDsc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="NVarChar(20)")] string changeDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, activeOrNo, deActiveDsc, user_Id, changeDateTime, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientUpdate")]
		public int SP_PatientUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreateDate", DbType="NVarChar(20)")] string createDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo", DbType="NVarChar(100)")] string dosiersNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientName", DbType="NVarChar(50)")] string patientName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientFamily", DbType="NVarChar(50)")] string patientFamily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentName", DbType="NVarChar(50)")] string parentName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sex", DbType="TinyInt")] System.Nullable<byte> sex, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNO", DbType="NVarChar(50)")] string iDNO, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode", DbType="NVarChar(10)")] string nationalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Martyr_Id", DbType="Int")] System.Nullable<int> martyr_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientTypeStr", DbType="NVarChar(200)")] string patientTypeStr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InjuryTypeStr", DbType="NVarChar(200)")] string injuryTypeStr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate", DbType="NVarChar(10)")] string brithDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithCityName", DbType="NVarChar(50)")] string brithCityName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PercentState", DbType="SmallInt")] System.Nullable<short> percentState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SingleOrNo", DbType="NVarChar(50)")] string singleOrNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BonyadAddEven", DbType="SmallInt")] System.Nullable<short> bonyadAddEven, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BonyadDosier", DbType="NVarChar(50)")] string bonyadDosier, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatePart", DbType="NVarChar(50)")] string statePart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityState", DbType="NVarChar(50)")] string cityState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CityPart", DbType="NVarChar(50)")] string cityPart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstitutePart", DbType="SmallInt")] System.Nullable<short> institutePart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddressPart", DbType="SmallInt")] System.Nullable<short> addressPart, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(4000)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalCode", DbType="NVarChar(50)")] string postalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelHome", DbType="NVarChar(50)")] string telHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelBusiness", DbType="NVarChar(50)")] string telBusiness, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(50)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile2", DbType="NVarChar(50)")] string mobile2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BasicInsurance", DbType="NVarChar(50)")] string basicInsurance, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CompletionInsurance", DbType="NVarChar(50)")] string completionInsurance, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastDoctorVisit_Id", DbType="Int")] System.Nullable<int> lastDoctorVisit_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastVisitDate", DbType="NVarChar(20)")] string lastVisitDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastDoctorPhysiotherapy_Id", DbType="Int")] System.Nullable<int> lastDoctorPhysiotherapy_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastPhysiotherapyDate", DbType="NVarChar(20)")] string lastPhysiotherapyDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastDoctorHealthCare_Id", DbType="Int")] System.Nullable<int> lastDoctorHealthCare_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastHealthCareDate", DbType="NVarChar(20)")] string lastHealthCareDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastVisitPatientCare_Id", DbType="BigInt")] System.Nullable<long> lastVisitPatientCare_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastCareDate", DbType="NVarChar(20)")] string lastCareDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bank_Id", DbType="SmallInt")] System.Nullable<short> bank_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNo1", DbType="NVarChar(1000)")] string accountNo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNo2", DbType="NVarChar(1000)")] string accountNo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountNo3", DbType="NVarChar(1000)")] string accountNo3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(1000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeActiveDsc", DbType="NVarChar(200)")] string deActiveDsc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="NVarChar(20)")] string changeDateTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, createDate, dosiersNo, patientName, patientFamily, parentName, sex, iDNO, nationalCode, martyr_Id, patientTypeStr, injuryTypeStr, brithDate, brithCityName, percentState, singleOrNo, bonyadAddEven, bonyadDosier, statePart, cityState, cityPart, institutePart, addressPart, address, postalCode, telHome, telBusiness, mobile, mobile2, email, basicInsurance, completionInsurance, lastDoctorVisit_Id, lastVisitDate, lastDoctorPhysiotherapy_Id, lastPhysiotherapyDate, lastDoctorHealthCare_Id, lastHealthCareDate, lastVisitPatientCare_Id, lastCareDate, bank_Id, accountNo1, accountNo2, accountNo3, description, deActiveDsc, active, user_Id, changeDateTime, msgRet);
			msgRet = ((string)(result.GetParameterValue(49)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PatientUpdateWithFieldValue")]
		public int SP_PatientUpdateWithFieldValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FieldName", DbType="NVarChar(50)")] string fieldName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FieldValue", DbType="NVarChar(200)")] string fieldValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="NVarChar(20)")] string changeDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, fieldName, fieldValue, user_Id, changeDateTime, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_TableNameUpdateWithNullValue")]
		public int SP_TableNameUpdateWithNullValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TableName", DbType="VarChar(50)")] string tableName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FieldName", DbType="NVarChar(50)")] string fieldName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Id", DbType="Int")] System.Nullable<int> user_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangeDateTime", DbType="NVarChar(20)")] string changeDateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, tableName, fieldName, user_Id, changeDateTime, msgRet);
			msgRet = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PatientStateSickness")]
	public partial class TBL_PatientStateSickness : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Patient_Id;
		
		private int _StateSicknessDetail_Id;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatient_IdChanging(long value);
    partial void OnPatient_IdChanged();
    partial void OnStateSicknessDetail_IdChanging(int value);
    partial void OnStateSicknessDetail_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_PatientStateSickness()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Patient_Id
		{
			get
			{
				return this._Patient_Id;
			}
			set
			{
				if ((this._Patient_Id != value))
				{
					this.OnPatient_IdChanging(value);
					this.SendPropertyChanging();
					this._Patient_Id = value;
					this.SendPropertyChanged("Patient_Id");
					this.OnPatient_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateSicknessDetail_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int StateSicknessDetail_Id
		{
			get
			{
				return this._StateSicknessDetail_Id;
			}
			set
			{
				if ((this._StateSicknessDetail_Id != value))
				{
					this.OnStateSicknessDetail_IdChanging(value);
					this.SendPropertyChanging();
					this._StateSicknessDetail_Id = value;
					this.SendPropertyChanged("StateSicknessDetail_Id");
					this.OnStateSicknessDetail_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_PatientStateSickness")]
	public partial class VW_PatientStateSickness
	{
		
		private long _Patient_Id;
		
		private int _StateSicknessDetail_Id;
		
		private string _Description;
		
		public VW_PatientStateSickness()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Id", DbType="BigInt NOT NULL")]
		public long Patient_Id
		{
			get
			{
				return this._Patient_Id;
			}
			set
			{
				if ((this._Patient_Id != value))
				{
					this._Patient_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateSicknessDetail_Id", DbType="Int NOT NULL")]
		public int StateSicknessDetail_Id
		{
			get
			{
				return this._StateSicknessDetail_Id;
			}
			set
			{
				if ((this._StateSicknessDetail_Id != value))
				{
					this._StateSicknessDetail_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_Patient")]
	public partial class VW_Patient
	{
		
		private int _Id;
		
		private string _CreateDate;
		
		private string _DosiersNo;
		
		private string _PatientName;
		
		private string _PatientFamily;
		
		private string _ParentName;
		
		private string _SexStr;
		
		private System.Nullable<byte> _Sex;
		
		private string _IDNO;
		
		private string _NationalCode;
		
		private System.Nullable<int> _Martyr_Id;
		
		private string _PatientTypeStr;
		
		private string _InjuryTypeStr;
		
		private string _BrithDate;
		
		private string _BrithCityName;
		
		private System.Nullable<short> _PercentState;
		
		private string _CityPart;
		
		private System.Nullable<short> _InstitutePart;
		
		private System.Nullable<short> _AddressPart;
		
		private string _Address;
		
		private string _PostalCode;
		
		private string _TelHome;
		
		private string _TelBusiness;
		
		private string _Mobile;
		
		private string _Mobile2;
		
		private string _Email;
		
		private string _BasicInsurance;
		
		private string _CompletionInsurance;
		
		private string _AccountNo1;
		
		private string _AccountNo2;
		
		private string _AccountNo3;
		
		private string _Description;
		
		private string _DeActiveDsc;
		
		private System.Nullable<bool> _Active;
		
		private string _MartyrNameFamily;
		
		private System.Nullable<short> _Bank_Id;
		
		private string _BankName;
		
		private string _NationalCode1;
		
		private string _MartyrName1;
		
		private string _MartyrDate1;
		
		private System.Nullable<short> _MartyrFew;
		
		private string _SingleOrNo;
		
		private System.Nullable<short> _BonyadAddEven;
		
		private string _BonyadAddEvenStr;
		
		private System.Nullable<int> _LastDoctorPhysiotherapy_Id;
		
		private string _LastPhysiotherapyDate;
		
		private System.Nullable<int> _LastDoctorHealthCare_Id;
		
		private string _LastCareDate;
		
		private string _LastHealthCareDate;
		
		private string _LastVisitDate;
		
		private System.Nullable<int> _LastDoctorVisit_Id;
		
		private string _LastDoctorVisitNameF;
		
		private string _LastDoctorPhysiotherapyNameF;
		
		private string _LastDoctorHealthCareNameF;
		
		private string _LastVisitPatientCareNameF;
		
		private System.Nullable<long> _LastVisitPatientCare_Id;
		
		private System.Nullable<int> _User_Id;
		
		private string _ChangeDateTime;
		
		private string _UsersNameFamily;
		
		private string _BonyadDosier;
		
		private string _StatePart;
		
		private string _CityState;
		
		public VW_Patient()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
		public string CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo", DbType="NVarChar(100)")]
		public string DosiersNo
		{
			get
			{
				return this._DosiersNo;
			}
			set
			{
				if ((this._DosiersNo != value))
				{
					this._DosiersNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(50)")]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientFamily", DbType="NVarChar(50)")]
		public string PatientFamily
		{
			get
			{
				return this._PatientFamily;
			}
			set
			{
				if ((this._PatientFamily != value))
				{
					this._PatientFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentName", DbType="NVarChar(50)")]
		public string ParentName
		{
			get
			{
				return this._ParentName;
			}
			set
			{
				if ((this._ParentName != value))
				{
					this._ParentName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexStr", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string SexStr
		{
			get
			{
				return this._SexStr;
			}
			set
			{
				if ((this._SexStr != value))
				{
					this._SexStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="TinyInt")]
		public System.Nullable<byte> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="NVarChar(50)")]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this._IDNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NationalCode
		{
			get
			{
				return this._NationalCode;
			}
			set
			{
				if ((this._NationalCode != value))
				{
					this._NationalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Martyr_Id", DbType="Int")]
		public System.Nullable<int> Martyr_Id
		{
			get
			{
				return this._Martyr_Id;
			}
			set
			{
				if ((this._Martyr_Id != value))
				{
					this._Martyr_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientTypeStr", DbType="NVarChar(200)")]
		public string PatientTypeStr
		{
			get
			{
				return this._PatientTypeStr;
			}
			set
			{
				if ((this._PatientTypeStr != value))
				{
					this._PatientTypeStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InjuryTypeStr", DbType="NVarChar(200)")]
		public string InjuryTypeStr
		{
			get
			{
				return this._InjuryTypeStr;
			}
			set
			{
				if ((this._InjuryTypeStr != value))
				{
					this._InjuryTypeStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate", DbType="NVarChar(50)")]
		public string BrithDate
		{
			get
			{
				return this._BrithDate;
			}
			set
			{
				if ((this._BrithDate != value))
				{
					this._BrithDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithCityName", DbType="NVarChar(50)")]
		public string BrithCityName
		{
			get
			{
				return this._BrithCityName;
			}
			set
			{
				if ((this._BrithCityName != value))
				{
					this._BrithCityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentState", DbType="SmallInt")]
		public System.Nullable<short> PercentState
		{
			get
			{
				return this._PercentState;
			}
			set
			{
				if ((this._PercentState != value))
				{
					this._PercentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityPart", DbType="NVarChar(50)")]
		public string CityPart
		{
			get
			{
				return this._CityPart;
			}
			set
			{
				if ((this._CityPart != value))
				{
					this._CityPart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutePart", DbType="SmallInt")]
		public System.Nullable<short> InstitutePart
		{
			get
			{
				return this._InstitutePart;
			}
			set
			{
				if ((this._InstitutePart != value))
				{
					this._InstitutePart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressPart", DbType="SmallInt")]
		public System.Nullable<short> AddressPart
		{
			get
			{
				return this._AddressPart;
			}
			set
			{
				if ((this._AddressPart != value))
				{
					this._AddressPart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(4000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(50)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="NVarChar(50)")]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this._TelHome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelBusiness", DbType="NVarChar(50)")]
		public string TelBusiness
		{
			get
			{
				return this._TelBusiness;
			}
			set
			{
				if ((this._TelBusiness != value))
				{
					this._TelBusiness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile2", DbType="NVarChar(50)")]
		public string Mobile2
		{
			get
			{
				return this._Mobile2;
			}
			set
			{
				if ((this._Mobile2 != value))
				{
					this._Mobile2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicInsurance", DbType="NVarChar(50)")]
		public string BasicInsurance
		{
			get
			{
				return this._BasicInsurance;
			}
			set
			{
				if ((this._BasicInsurance != value))
				{
					this._BasicInsurance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletionInsurance", DbType="NVarChar(50)")]
		public string CompletionInsurance
		{
			get
			{
				return this._CompletionInsurance;
			}
			set
			{
				if ((this._CompletionInsurance != value))
				{
					this._CompletionInsurance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo1", DbType="NVarChar(1000)")]
		public string AccountNo1
		{
			get
			{
				return this._AccountNo1;
			}
			set
			{
				if ((this._AccountNo1 != value))
				{
					this._AccountNo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo2", DbType="NVarChar(1000)")]
		public string AccountNo2
		{
			get
			{
				return this._AccountNo2;
			}
			set
			{
				if ((this._AccountNo2 != value))
				{
					this._AccountNo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo3", DbType="NVarChar(1000)")]
		public string AccountNo3
		{
			get
			{
				return this._AccountNo3;
			}
			set
			{
				if ((this._AccountNo3 != value))
				{
					this._AccountNo3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeActiveDsc", DbType="NVarChar(200)")]
		public string DeActiveDsc
		{
			get
			{
				return this._DeActiveDsc;
			}
			set
			{
				if ((this._DeActiveDsc != value))
				{
					this._DeActiveDsc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrNameFamily", DbType="VarChar(500)")]
		public string MartyrNameFamily
		{
			get
			{
				return this._MartyrNameFamily;
			}
			set
			{
				if ((this._MartyrNameFamily != value))
				{
					this._MartyrNameFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_Id", DbType="SmallInt")]
		public System.Nullable<short> Bank_Id
		{
			get
			{
				return this._Bank_Id;
			}
			set
			{
				if ((this._Bank_Id != value))
				{
					this._Bank_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(50)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this._BankName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode1", DbType="VarChar(10)")]
		public string NationalCode1
		{
			get
			{
				return this._NationalCode1;
			}
			set
			{
				if ((this._NationalCode1 != value))
				{
					this._NationalCode1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrName1", DbType="VarChar(50)")]
		public string MartyrName1
		{
			get
			{
				return this._MartyrName1;
			}
			set
			{
				if ((this._MartyrName1 != value))
				{
					this._MartyrName1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrDate1", DbType="VarChar(20)")]
		public string MartyrDate1
		{
			get
			{
				return this._MartyrDate1;
			}
			set
			{
				if ((this._MartyrDate1 != value))
				{
					this._MartyrDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrFew", DbType="SmallInt")]
		public System.Nullable<short> MartyrFew
		{
			get
			{
				return this._MartyrFew;
			}
			set
			{
				if ((this._MartyrFew != value))
				{
					this._MartyrFew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SingleOrNo", DbType="NVarChar(50)")]
		public string SingleOrNo
		{
			get
			{
				return this._SingleOrNo;
			}
			set
			{
				if ((this._SingleOrNo != value))
				{
					this._SingleOrNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadAddEven", DbType="SmallInt")]
		public System.Nullable<short> BonyadAddEven
		{
			get
			{
				return this._BonyadAddEven;
			}
			set
			{
				if ((this._BonyadAddEven != value))
				{
					this._BonyadAddEven = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadAddEvenStr", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string BonyadAddEvenStr
		{
			get
			{
				return this._BonyadAddEvenStr;
			}
			set
			{
				if ((this._BonyadAddEvenStr != value))
				{
					this._BonyadAddEvenStr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorPhysiotherapy_Id", DbType="Int")]
		public System.Nullable<int> LastDoctorPhysiotherapy_Id
		{
			get
			{
				return this._LastDoctorPhysiotherapy_Id;
			}
			set
			{
				if ((this._LastDoctorPhysiotherapy_Id != value))
				{
					this._LastDoctorPhysiotherapy_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPhysiotherapyDate", DbType="NVarChar(50)")]
		public string LastPhysiotherapyDate
		{
			get
			{
				return this._LastPhysiotherapyDate;
			}
			set
			{
				if ((this._LastPhysiotherapyDate != value))
				{
					this._LastPhysiotherapyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorHealthCare_Id", DbType="Int")]
		public System.Nullable<int> LastDoctorHealthCare_Id
		{
			get
			{
				return this._LastDoctorHealthCare_Id;
			}
			set
			{
				if ((this._LastDoctorHealthCare_Id != value))
				{
					this._LastDoctorHealthCare_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCareDate", DbType="NVarChar(50)")]
		public string LastCareDate
		{
			get
			{
				return this._LastCareDate;
			}
			set
			{
				if ((this._LastCareDate != value))
				{
					this._LastCareDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastHealthCareDate", DbType="NVarChar(50)")]
		public string LastHealthCareDate
		{
			get
			{
				return this._LastHealthCareDate;
			}
			set
			{
				if ((this._LastHealthCareDate != value))
				{
					this._LastHealthCareDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitDate", DbType="NVarChar(50)")]
		public string LastVisitDate
		{
			get
			{
				return this._LastVisitDate;
			}
			set
			{
				if ((this._LastVisitDate != value))
				{
					this._LastVisitDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorVisit_Id", DbType="Int")]
		public System.Nullable<int> LastDoctorVisit_Id
		{
			get
			{
				return this._LastDoctorVisit_Id;
			}
			set
			{
				if ((this._LastDoctorVisit_Id != value))
				{
					this._LastDoctorVisit_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorVisitNameF", DbType="VarChar(101)")]
		public string LastDoctorVisitNameF
		{
			get
			{
				return this._LastDoctorVisitNameF;
			}
			set
			{
				if ((this._LastDoctorVisitNameF != value))
				{
					this._LastDoctorVisitNameF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorPhysiotherapyNameF", DbType="VarChar(101)")]
		public string LastDoctorPhysiotherapyNameF
		{
			get
			{
				return this._LastDoctorPhysiotherapyNameF;
			}
			set
			{
				if ((this._LastDoctorPhysiotherapyNameF != value))
				{
					this._LastDoctorPhysiotherapyNameF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorHealthCareNameF", DbType="VarChar(101)")]
		public string LastDoctorHealthCareNameF
		{
			get
			{
				return this._LastDoctorHealthCareNameF;
			}
			set
			{
				if ((this._LastDoctorHealthCareNameF != value))
				{
					this._LastDoctorHealthCareNameF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitPatientCareNameF", DbType="VarChar(101)")]
		public string LastVisitPatientCareNameF
		{
			get
			{
				return this._LastVisitPatientCareNameF;
			}
			set
			{
				if ((this._LastVisitPatientCareNameF != value))
				{
					this._LastVisitPatientCareNameF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitPatientCare_Id", DbType="BigInt")]
		public System.Nullable<long> LastVisitPatientCare_Id
		{
			get
			{
				return this._LastVisitPatientCare_Id;
			}
			set
			{
				if ((this._LastVisitPatientCare_Id != value))
				{
					this._LastVisitPatientCare_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int")]
		public System.Nullable<int> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this._User_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeDateTime", DbType="NVarChar(50)")]
		public string ChangeDateTime
		{
			get
			{
				return this._ChangeDateTime;
			}
			set
			{
				if ((this._ChangeDateTime != value))
				{
					this._ChangeDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersNameFamily", DbType="VarChar(201)")]
		public string UsersNameFamily
		{
			get
			{
				return this._UsersNameFamily;
			}
			set
			{
				if ((this._UsersNameFamily != value))
				{
					this._UsersNameFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadDosier", DbType="NVarChar(50)")]
		public string BonyadDosier
		{
			get
			{
				return this._BonyadDosier;
			}
			set
			{
				if ((this._BonyadDosier != value))
				{
					this._BonyadDosier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatePart", DbType="NVarChar(50)")]
		public string StatePart
		{
			get
			{
				return this._StatePart;
			}
			set
			{
				if ((this._StatePart != value))
				{
					this._StatePart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityState", DbType="NVarChar(50)")]
		public string CityState
		{
			get
			{
				return this._CityState;
			}
			set
			{
				if ((this._CityState != value))
				{
					this._CityState = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Patient")]
	public partial class TBL_Patient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _PatientNo;
		
		private string _CreateDate;
		
		private string _DosiersNo;
		
		private string _PatientName;
		
		private string _PatientFamily;
		
		private string _ParentName;
		
		private System.Nullable<byte> _Sex;
		
		private string _IDNO;
		
		private string _NationalCode;
		
		private System.Nullable<int> _Martyr_Id;
		
		private string _PatientTypeStr;
		
		private string _InjuryTypeStr;
		
		private string _BrithDate;
		
		private string _BrithCityName;
		
		private System.Nullable<short> _PercentState;
		
		private string _SingleOrNo;
		
		private System.Nullable<short> _BonyadAddEven;
		
		private string _BonyadDosier;
		
		private string _StatePart;
		
		private string _CityState;
		
		private string _CityPart;
		
		private System.Nullable<short> _InstitutePart;
		
		private System.Nullable<short> _AddressPart;
		
		private string _Address;
		
		private string _PostalCode;
		
		private string _TelHome;
		
		private string _TelBusiness;
		
		private string _Mobile;
		
		private string _Mobile2;
		
		private string _Email;
		
		private string _BasicInsurance;
		
		private string _CompletionInsurance;
		
		private System.Nullable<int> _LastDoctorVisit_Id;
		
		private string _LastVisitDate;
		
		private System.Nullable<int> _LastDoctorPhysiotherapy_Id;
		
		private string _LastPhysiotherapyDate;
		
		private System.Nullable<int> _LastDoctorHealthCare_Id;
		
		private string _LastHealthCareDate;
		
		private System.Nullable<long> _LastVisitPatientCare_Id;
		
		private string _LastCareDate;
		
		private System.Nullable<short> _Bank_Id;
		
		private string _AccountNo1;
		
		private string _AccountNo2;
		
		private string _AccountNo3;
		
		private string _Description;
		
		private string _DeActiveDsc;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _User_Id;
		
		private string _ChangeDateTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPatientNoChanging(string value);
    partial void OnPatientNoChanged();
    partial void OnCreateDateChanging(string value);
    partial void OnCreateDateChanged();
    partial void OnDosiersNoChanging(string value);
    partial void OnDosiersNoChanged();
    partial void OnPatientNameChanging(string value);
    partial void OnPatientNameChanged();
    partial void OnPatientFamilyChanging(string value);
    partial void OnPatientFamilyChanged();
    partial void OnParentNameChanging(string value);
    partial void OnParentNameChanged();
    partial void OnSexChanging(System.Nullable<byte> value);
    partial void OnSexChanged();
    partial void OnIDNOChanging(string value);
    partial void OnIDNOChanged();
    partial void OnNationalCodeChanging(string value);
    partial void OnNationalCodeChanged();
    partial void OnMartyr_IdChanging(System.Nullable<int> value);
    partial void OnMartyr_IdChanged();
    partial void OnPatientTypeStrChanging(string value);
    partial void OnPatientTypeStrChanged();
    partial void OnInjuryTypeStrChanging(string value);
    partial void OnInjuryTypeStrChanged();
    partial void OnBrithDateChanging(string value);
    partial void OnBrithDateChanged();
    partial void OnBrithCityNameChanging(string value);
    partial void OnBrithCityNameChanged();
    partial void OnPercentStateChanging(System.Nullable<short> value);
    partial void OnPercentStateChanged();
    partial void OnSingleOrNoChanging(string value);
    partial void OnSingleOrNoChanged();
    partial void OnBonyadAddEvenChanging(System.Nullable<short> value);
    partial void OnBonyadAddEvenChanged();
    partial void OnBonyadDosierChanging(string value);
    partial void OnBonyadDosierChanged();
    partial void OnStatePartChanging(string value);
    partial void OnStatePartChanged();
    partial void OnCityStateChanging(string value);
    partial void OnCityStateChanged();
    partial void OnCityPartChanging(string value);
    partial void OnCityPartChanged();
    partial void OnInstitutePartChanging(System.Nullable<short> value);
    partial void OnInstitutePartChanged();
    partial void OnAddressPartChanging(System.Nullable<short> value);
    partial void OnAddressPartChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnTelHomeChanging(string value);
    partial void OnTelHomeChanged();
    partial void OnTelBusinessChanging(string value);
    partial void OnTelBusinessChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnMobile2Changing(string value);
    partial void OnMobile2Changed();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnBasicInsuranceChanging(string value);
    partial void OnBasicInsuranceChanged();
    partial void OnCompletionInsuranceChanging(string value);
    partial void OnCompletionInsuranceChanged();
    partial void OnLastDoctorVisit_IdChanging(System.Nullable<int> value);
    partial void OnLastDoctorVisit_IdChanged();
    partial void OnLastVisitDateChanging(string value);
    partial void OnLastVisitDateChanged();
    partial void OnLastDoctorPhysiotherapy_IdChanging(System.Nullable<int> value);
    partial void OnLastDoctorPhysiotherapy_IdChanged();
    partial void OnLastPhysiotherapyDateChanging(string value);
    partial void OnLastPhysiotherapyDateChanged();
    partial void OnLastDoctorHealthCare_IdChanging(System.Nullable<int> value);
    partial void OnLastDoctorHealthCare_IdChanged();
    partial void OnLastHealthCareDateChanging(string value);
    partial void OnLastHealthCareDateChanged();
    partial void OnLastVisitPatientCare_IdChanging(System.Nullable<long> value);
    partial void OnLastVisitPatientCare_IdChanged();
    partial void OnLastCareDateChanging(string value);
    partial void OnLastCareDateChanged();
    partial void OnBank_IdChanging(System.Nullable<short> value);
    partial void OnBank_IdChanged();
    partial void OnAccountNo1Changing(string value);
    partial void OnAccountNo1Changed();
    partial void OnAccountNo2Changing(string value);
    partial void OnAccountNo2Changed();
    partial void OnAccountNo3Changing(string value);
    partial void OnAccountNo3Changed();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnDeActiveDscChanging(string value);
    partial void OnDeActiveDscChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnUser_IdChanging(System.Nullable<int> value);
    partial void OnUser_IdChanged();
    partial void OnChangeDateTimeChanging(string value);
    partial void OnChangeDateTimeChanged();
    #endregion
		
		public TBL_Patient()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNo", DbType="NVarChar(50)")]
		public string PatientNo
		{
			get
			{
				return this._PatientNo;
			}
			set
			{
				if ((this._PatientNo != value))
				{
					this.OnPatientNoChanging(value);
					this.SendPropertyChanging();
					this._PatientNo = value;
					this.SendPropertyChanged("PatientNo");
					this.OnPatientNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="NVarChar(50)")]
		public string CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo", DbType="NVarChar(100)")]
		public string DosiersNo
		{
			get
			{
				return this._DosiersNo;
			}
			set
			{
				if ((this._DosiersNo != value))
				{
					this.OnDosiersNoChanging(value);
					this.SendPropertyChanging();
					this._DosiersNo = value;
					this.SendPropertyChanged("DosiersNo");
					this.OnDosiersNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(50)")]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this.OnPatientNameChanging(value);
					this.SendPropertyChanging();
					this._PatientName = value;
					this.SendPropertyChanged("PatientName");
					this.OnPatientNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientFamily", DbType="NVarChar(50)")]
		public string PatientFamily
		{
			get
			{
				return this._PatientFamily;
			}
			set
			{
				if ((this._PatientFamily != value))
				{
					this.OnPatientFamilyChanging(value);
					this.SendPropertyChanging();
					this._PatientFamily = value;
					this.SendPropertyChanged("PatientFamily");
					this.OnPatientFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentName", DbType="NVarChar(50)")]
		public string ParentName
		{
			get
			{
				return this._ParentName;
			}
			set
			{
				if ((this._ParentName != value))
				{
					this.OnParentNameChanging(value);
					this.SendPropertyChanging();
					this._ParentName = value;
					this.SendPropertyChanged("ParentName");
					this.OnParentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="TinyInt")]
		public System.Nullable<byte> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="NVarChar(50)")]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this.OnIDNOChanging(value);
					this.SendPropertyChanging();
					this._IDNO = value;
					this.SendPropertyChanged("IDNO");
					this.OnIDNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NationalCode
		{
			get
			{
				return this._NationalCode;
			}
			set
			{
				if ((this._NationalCode != value))
				{
					this.OnNationalCodeChanging(value);
					this.SendPropertyChanging();
					this._NationalCode = value;
					this.SendPropertyChanged("NationalCode");
					this.OnNationalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Martyr_Id", DbType="Int")]
		public System.Nullable<int> Martyr_Id
		{
			get
			{
				return this._Martyr_Id;
			}
			set
			{
				if ((this._Martyr_Id != value))
				{
					this.OnMartyr_IdChanging(value);
					this.SendPropertyChanging();
					this._Martyr_Id = value;
					this.SendPropertyChanged("Martyr_Id");
					this.OnMartyr_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientTypeStr", DbType="NVarChar(200)")]
		public string PatientTypeStr
		{
			get
			{
				return this._PatientTypeStr;
			}
			set
			{
				if ((this._PatientTypeStr != value))
				{
					this.OnPatientTypeStrChanging(value);
					this.SendPropertyChanging();
					this._PatientTypeStr = value;
					this.SendPropertyChanged("PatientTypeStr");
					this.OnPatientTypeStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InjuryTypeStr", DbType="NVarChar(200)")]
		public string InjuryTypeStr
		{
			get
			{
				return this._InjuryTypeStr;
			}
			set
			{
				if ((this._InjuryTypeStr != value))
				{
					this.OnInjuryTypeStrChanging(value);
					this.SendPropertyChanging();
					this._InjuryTypeStr = value;
					this.SendPropertyChanged("InjuryTypeStr");
					this.OnInjuryTypeStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate", DbType="NVarChar(50)")]
		public string BrithDate
		{
			get
			{
				return this._BrithDate;
			}
			set
			{
				if ((this._BrithDate != value))
				{
					this.OnBrithDateChanging(value);
					this.SendPropertyChanging();
					this._BrithDate = value;
					this.SendPropertyChanged("BrithDate");
					this.OnBrithDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithCityName", DbType="NVarChar(50)")]
		public string BrithCityName
		{
			get
			{
				return this._BrithCityName;
			}
			set
			{
				if ((this._BrithCityName != value))
				{
					this.OnBrithCityNameChanging(value);
					this.SendPropertyChanging();
					this._BrithCityName = value;
					this.SendPropertyChanged("BrithCityName");
					this.OnBrithCityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PercentState", DbType="SmallInt")]
		public System.Nullable<short> PercentState
		{
			get
			{
				return this._PercentState;
			}
			set
			{
				if ((this._PercentState != value))
				{
					this.OnPercentStateChanging(value);
					this.SendPropertyChanging();
					this._PercentState = value;
					this.SendPropertyChanged("PercentState");
					this.OnPercentStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SingleOrNo", DbType="NVarChar(50)")]
		public string SingleOrNo
		{
			get
			{
				return this._SingleOrNo;
			}
			set
			{
				if ((this._SingleOrNo != value))
				{
					this.OnSingleOrNoChanging(value);
					this.SendPropertyChanging();
					this._SingleOrNo = value;
					this.SendPropertyChanged("SingleOrNo");
					this.OnSingleOrNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadAddEven", DbType="SmallInt")]
		public System.Nullable<short> BonyadAddEven
		{
			get
			{
				return this._BonyadAddEven;
			}
			set
			{
				if ((this._BonyadAddEven != value))
				{
					this.OnBonyadAddEvenChanging(value);
					this.SendPropertyChanging();
					this._BonyadAddEven = value;
					this.SendPropertyChanged("BonyadAddEven");
					this.OnBonyadAddEvenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonyadDosier", DbType="NVarChar(50)")]
		public string BonyadDosier
		{
			get
			{
				return this._BonyadDosier;
			}
			set
			{
				if ((this._BonyadDosier != value))
				{
					this.OnBonyadDosierChanging(value);
					this.SendPropertyChanging();
					this._BonyadDosier = value;
					this.SendPropertyChanged("BonyadDosier");
					this.OnBonyadDosierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatePart", DbType="NVarChar(50)")]
		public string StatePart
		{
			get
			{
				return this._StatePart;
			}
			set
			{
				if ((this._StatePart != value))
				{
					this.OnStatePartChanging(value);
					this.SendPropertyChanging();
					this._StatePart = value;
					this.SendPropertyChanged("StatePart");
					this.OnStatePartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityState", DbType="NVarChar(50)")]
		public string CityState
		{
			get
			{
				return this._CityState;
			}
			set
			{
				if ((this._CityState != value))
				{
					this.OnCityStateChanging(value);
					this.SendPropertyChanging();
					this._CityState = value;
					this.SendPropertyChanged("CityState");
					this.OnCityStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityPart", DbType="NVarChar(50)")]
		public string CityPart
		{
			get
			{
				return this._CityPart;
			}
			set
			{
				if ((this._CityPart != value))
				{
					this.OnCityPartChanging(value);
					this.SendPropertyChanging();
					this._CityPart = value;
					this.SendPropertyChanged("CityPart");
					this.OnCityPartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutePart", DbType="SmallInt")]
		public System.Nullable<short> InstitutePart
		{
			get
			{
				return this._InstitutePart;
			}
			set
			{
				if ((this._InstitutePart != value))
				{
					this.OnInstitutePartChanging(value);
					this.SendPropertyChanging();
					this._InstitutePart = value;
					this.SendPropertyChanged("InstitutePart");
					this.OnInstitutePartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressPart", DbType="SmallInt")]
		public System.Nullable<short> AddressPart
		{
			get
			{
				return this._AddressPart;
			}
			set
			{
				if ((this._AddressPart != value))
				{
					this.OnAddressPartChanging(value);
					this.SendPropertyChanging();
					this._AddressPart = value;
					this.SendPropertyChanged("AddressPart");
					this.OnAddressPartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(4000)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(50)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="NVarChar(50)")]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this.OnTelHomeChanging(value);
					this.SendPropertyChanging();
					this._TelHome = value;
					this.SendPropertyChanged("TelHome");
					this.OnTelHomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelBusiness", DbType="NVarChar(50)")]
		public string TelBusiness
		{
			get
			{
				return this._TelBusiness;
			}
			set
			{
				if ((this._TelBusiness != value))
				{
					this.OnTelBusinessChanging(value);
					this.SendPropertyChanging();
					this._TelBusiness = value;
					this.SendPropertyChanged("TelBusiness");
					this.OnTelBusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile2", DbType="NVarChar(50)")]
		public string Mobile2
		{
			get
			{
				return this._Mobile2;
			}
			set
			{
				if ((this._Mobile2 != value))
				{
					this.OnMobile2Changing(value);
					this.SendPropertyChanging();
					this._Mobile2 = value;
					this.SendPropertyChanged("Mobile2");
					this.OnMobile2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicInsurance", DbType="NVarChar(50)")]
		public string BasicInsurance
		{
			get
			{
				return this._BasicInsurance;
			}
			set
			{
				if ((this._BasicInsurance != value))
				{
					this.OnBasicInsuranceChanging(value);
					this.SendPropertyChanging();
					this._BasicInsurance = value;
					this.SendPropertyChanged("BasicInsurance");
					this.OnBasicInsuranceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletionInsurance", DbType="NVarChar(50)")]
		public string CompletionInsurance
		{
			get
			{
				return this._CompletionInsurance;
			}
			set
			{
				if ((this._CompletionInsurance != value))
				{
					this.OnCompletionInsuranceChanging(value);
					this.SendPropertyChanging();
					this._CompletionInsurance = value;
					this.SendPropertyChanged("CompletionInsurance");
					this.OnCompletionInsuranceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorVisit_Id", DbType="Int")]
		public System.Nullable<int> LastDoctorVisit_Id
		{
			get
			{
				return this._LastDoctorVisit_Id;
			}
			set
			{
				if ((this._LastDoctorVisit_Id != value))
				{
					this.OnLastDoctorVisit_IdChanging(value);
					this.SendPropertyChanging();
					this._LastDoctorVisit_Id = value;
					this.SendPropertyChanged("LastDoctorVisit_Id");
					this.OnLastDoctorVisit_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitDate", DbType="NVarChar(50)")]
		public string LastVisitDate
		{
			get
			{
				return this._LastVisitDate;
			}
			set
			{
				if ((this._LastVisitDate != value))
				{
					this.OnLastVisitDateChanging(value);
					this.SendPropertyChanging();
					this._LastVisitDate = value;
					this.SendPropertyChanged("LastVisitDate");
					this.OnLastVisitDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorPhysiotherapy_Id", DbType="Int")]
		public System.Nullable<int> LastDoctorPhysiotherapy_Id
		{
			get
			{
				return this._LastDoctorPhysiotherapy_Id;
			}
			set
			{
				if ((this._LastDoctorPhysiotherapy_Id != value))
				{
					this.OnLastDoctorPhysiotherapy_IdChanging(value);
					this.SendPropertyChanging();
					this._LastDoctorPhysiotherapy_Id = value;
					this.SendPropertyChanged("LastDoctorPhysiotherapy_Id");
					this.OnLastDoctorPhysiotherapy_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPhysiotherapyDate", DbType="NVarChar(50)")]
		public string LastPhysiotherapyDate
		{
			get
			{
				return this._LastPhysiotherapyDate;
			}
			set
			{
				if ((this._LastPhysiotherapyDate != value))
				{
					this.OnLastPhysiotherapyDateChanging(value);
					this.SendPropertyChanging();
					this._LastPhysiotherapyDate = value;
					this.SendPropertyChanged("LastPhysiotherapyDate");
					this.OnLastPhysiotherapyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastDoctorHealthCare_Id", DbType="Int")]
		public System.Nullable<int> LastDoctorHealthCare_Id
		{
			get
			{
				return this._LastDoctorHealthCare_Id;
			}
			set
			{
				if ((this._LastDoctorHealthCare_Id != value))
				{
					this.OnLastDoctorHealthCare_IdChanging(value);
					this.SendPropertyChanging();
					this._LastDoctorHealthCare_Id = value;
					this.SendPropertyChanged("LastDoctorHealthCare_Id");
					this.OnLastDoctorHealthCare_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastHealthCareDate", DbType="NVarChar(50)")]
		public string LastHealthCareDate
		{
			get
			{
				return this._LastHealthCareDate;
			}
			set
			{
				if ((this._LastHealthCareDate != value))
				{
					this.OnLastHealthCareDateChanging(value);
					this.SendPropertyChanging();
					this._LastHealthCareDate = value;
					this.SendPropertyChanged("LastHealthCareDate");
					this.OnLastHealthCareDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitPatientCare_Id", DbType="BigInt")]
		public System.Nullable<long> LastVisitPatientCare_Id
		{
			get
			{
				return this._LastVisitPatientCare_Id;
			}
			set
			{
				if ((this._LastVisitPatientCare_Id != value))
				{
					this.OnLastVisitPatientCare_IdChanging(value);
					this.SendPropertyChanging();
					this._LastVisitPatientCare_Id = value;
					this.SendPropertyChanged("LastVisitPatientCare_Id");
					this.OnLastVisitPatientCare_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCareDate", DbType="NVarChar(50)")]
		public string LastCareDate
		{
			get
			{
				return this._LastCareDate;
			}
			set
			{
				if ((this._LastCareDate != value))
				{
					this.OnLastCareDateChanging(value);
					this.SendPropertyChanging();
					this._LastCareDate = value;
					this.SendPropertyChanged("LastCareDate");
					this.OnLastCareDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_Id", DbType="SmallInt")]
		public System.Nullable<short> Bank_Id
		{
			get
			{
				return this._Bank_Id;
			}
			set
			{
				if ((this._Bank_Id != value))
				{
					this.OnBank_IdChanging(value);
					this.SendPropertyChanging();
					this._Bank_Id = value;
					this.SendPropertyChanged("Bank_Id");
					this.OnBank_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo1", DbType="NVarChar(1000)")]
		public string AccountNo1
		{
			get
			{
				return this._AccountNo1;
			}
			set
			{
				if ((this._AccountNo1 != value))
				{
					this.OnAccountNo1Changing(value);
					this.SendPropertyChanging();
					this._AccountNo1 = value;
					this.SendPropertyChanged("AccountNo1");
					this.OnAccountNo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo2", DbType="NVarChar(1000)")]
		public string AccountNo2
		{
			get
			{
				return this._AccountNo2;
			}
			set
			{
				if ((this._AccountNo2 != value))
				{
					this.OnAccountNo2Changing(value);
					this.SendPropertyChanging();
					this._AccountNo2 = value;
					this.SendPropertyChanged("AccountNo2");
					this.OnAccountNo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo3", DbType="NVarChar(1000)")]
		public string AccountNo3
		{
			get
			{
				return this._AccountNo3;
			}
			set
			{
				if ((this._AccountNo3 != value))
				{
					this.OnAccountNo3Changing(value);
					this.SendPropertyChanging();
					this._AccountNo3 = value;
					this.SendPropertyChanged("AccountNo3");
					this.OnAccountNo3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeActiveDsc", DbType="NVarChar(200)")]
		public string DeActiveDsc
		{
			get
			{
				return this._DeActiveDsc;
			}
			set
			{
				if ((this._DeActiveDsc != value))
				{
					this.OnDeActiveDscChanging(value);
					this.SendPropertyChanging();
					this._DeActiveDsc = value;
					this.SendPropertyChanged("DeActiveDsc");
					this.OnDeActiveDscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int")]
		public System.Nullable<int> User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeDateTime", DbType="NVarChar(50)")]
		public string ChangeDateTime
		{
			get
			{
				return this._ChangeDateTime;
			}
			set
			{
				if ((this._ChangeDateTime != value))
				{
					this.OnChangeDateTimeChanging(value);
					this.SendPropertyChanging();
					this._ChangeDateTime = value;
					this.SendPropertyChanged("ChangeDateTime");
					this.OnChangeDateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
