#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysiotherapyCare.Model.VisitHealthCare
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhysiotherapyCare")]
	public partial class DataClassesVisitHealthCareBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_ServiceTypeDsc(TBL_ServiceTypeDsc instance);
    partial void UpdateTBL_ServiceTypeDsc(TBL_ServiceTypeDsc instance);
    partial void DeleteTBL_ServiceTypeDsc(TBL_ServiceTypeDsc instance);
    partial void InsertTBL_ServiceType(TBL_ServiceType instance);
    partial void UpdateTBL_ServiceType(TBL_ServiceType instance);
    partial void DeleteTBL_ServiceType(TBL_ServiceType instance);
    partial void InsertTBL_ServiceHealthCare(TBL_ServiceHealthCare instance);
    partial void UpdateTBL_ServiceHealthCare(TBL_ServiceHealthCare instance);
    partial void DeleteTBL_ServiceHealthCare(TBL_ServiceHealthCare instance);
    #endregion
		
		public DataClassesVisitHealthCareBaseDataContext() : 
				base(global::PhysiotherapyCare.Model.Properties.Settings.Default.PhysiotherapyCareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitHealthCareBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitHealthCareBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitHealthCareBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesVisitHealthCareBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_ServiceTypeDsc> TBL_ServiceTypeDscs
		{
			get
			{
				return this.GetTable<TBL_ServiceTypeDsc>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ServiceType> TBL_ServiceTypes
		{
			get
			{
				return this.GetTable<TBL_ServiceType>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ServiceHealthCare> TBL_ServiceHealthCares
		{
			get
			{
				return this.GetTable<TBL_ServiceHealthCare>();
			}
		}
		
		public System.Data.Linq.Table<VW_ServiceHealthCare> VW_ServiceHealthCares
		{
			get
			{
				return this.GetTable<VW_ServiceHealthCare>();
			}
		}
		
		public System.Data.Linq.Table<VW_ServiceType> VW_ServiceTypes
		{
			get
			{
				return this.GetTable<VW_ServiceType>();
			}
		}
		
		public System.Data.Linq.Table<VW_ServiceTypeDsc> VW_ServiceTypeDscs
		{
			get
			{
				return this.GetTable<VW_ServiceTypeDsc>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceHealthCareDelete")]
		public int SP_ServiceHealthCareDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitHealthCare_Id", DbType="BigInt")] System.Nullable<long> visitHealthCare_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceTypeDsc_Id", DbType="Int")] System.Nullable<int> serviceTypeDsc_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitHealthCare_Id, serviceTypeDsc_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceTypeDelete")]
		public int SP_ServiceTypeDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] System.Nullable<short> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceTypeDscDelete")]
		public int SP_ServiceTypeDscDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceHealthCareWithVisitHealthCareDelete")]
		public int SP_ServiceHealthCareWithVisitHealthCareDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitHealthCare_Id", DbType="BigInt")] System.Nullable<long> visitHealthCare_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitHealthCare_Id, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SumServiceHealthCare", IsComposable=true)]
		public System.Nullable<int> SumServiceHealthCare([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitHealthCare_Id", DbType="BigInt")] System.Nullable<long> visitHealthCare_Id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitHealthCare_Id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceHealthCareReportForDetailSum")]
		public ISingleResult<SP_ServiceHealthCareReportForDetailSumResult> SP_ServiceHealthCareReportForDetailSum([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateStart", DbType="VarChar(10)")] string dateStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateEnd", DbType="VarChar(10)")] string dateEnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateStart, dateEnd);
			return ((ISingleResult<SP_ServiceHealthCareReportForDetailSumResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceHealthCareReportForDetail")]
		public ISingleResult<SP_ServiceHealthCareReportForDetailResult> SP_ServiceHealthCareReportForDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateStart", DbType="VarChar(10)")] string dateStart, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateEnd", DbType="VarChar(10)")] string dateEnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateStart, dateEnd);
			return ((ISingleResult<SP_ServiceHealthCareReportForDetailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceHealthCareReportForDetailWithGroup")]
		public ISingleResult<SP_ServiceHealthCareReportForDetailWithGroupResult> SP_ServiceHealthCareReportForDetailWithGroup()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ServiceHealthCareReportForDetailWithGroupResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceHealthCareInsert")]
		public int SP_ServiceHealthCareInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitHealthCare_Id", DbType="BigInt")] System.Nullable<long> visitHealthCare_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceTypeDsc_Id", DbType="Int")] System.Nullable<int> serviceTypeDsc_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceTypeDscFew", DbType="Int")] System.Nullable<int> serviceTypeDscFew, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceType", DbType="Int")] System.Nullable<int> priceType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitHealthCare_Id, serviceTypeDsc_Id, serviceTypeDscFew, priceType, msgRet);
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceHealthCareUpdate")]
		public int SP_ServiceHealthCareUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitHealthCare_Id", DbType="BigInt")] System.Nullable<long> visitHealthCare_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceTypeDsc_Id", DbType="Int")] System.Nullable<int> serviceTypeDsc_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceTypeDscFew", DbType="Int")] System.Nullable<int> serviceTypeDscFew, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceType", DbType="Int")] System.Nullable<int> priceType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), visitHealthCare_Id, serviceTypeDsc_Id, serviceTypeDscFew, priceType, msgRet);
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceTypeDscInsert")]
		public int SP_ServiceTypeDscInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] ref System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceType_Id", DbType="SmallInt")] System.Nullable<short> serviceType_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitleName", DbType="NVarChar(100)")] string titleName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceType", DbType="Int")] System.Nullable<int> priceType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, serviceType_Id, titleName, priceType, msgRet);
			id = ((System.Nullable<int>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceTypeDscUpdate")]
		public int SP_ServiceTypeDscUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceType_Id", DbType="SmallInt")] System.Nullable<short> serviceType_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitleName", DbType="VarChar(100)")] string titleName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PriceType", DbType="Int")] System.Nullable<int> priceType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, serviceType_Id, titleName, priceType, msgRet);
			msgRet = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceTypeInsert")]
		public int SP_ServiceTypeInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] ref System.Nullable<short> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitleName", DbType="NVarChar(100)")] string titleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, titleName, msgRet);
			id = ((System.Nullable<short>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ServiceTypeUpdate")]
		public int SP_ServiceTypeUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="SmallInt")] System.Nullable<short> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TitleName", DbType="NVarChar(100)")] string titleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, titleName, msgRet);
			msgRet = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ServiceTypeDsc")]
	public partial class TBL_ServiceTypeDsc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<short> _ServiceType_Id;
		
		private string _TitleName;
		
		private System.Nullable<int> _PriceType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnServiceType_IdChanging(System.Nullable<short> value);
    partial void OnServiceType_IdChanged();
    partial void OnTitleNameChanging(string value);
    partial void OnTitleNameChanged();
    partial void OnPriceTypeChanging(System.Nullable<int> value);
    partial void OnPriceTypeChanged();
    #endregion
		
		public TBL_ServiceTypeDsc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceType_Id", DbType="SmallInt")]
		public System.Nullable<short> ServiceType_Id
		{
			get
			{
				return this._ServiceType_Id;
			}
			set
			{
				if ((this._ServiceType_Id != value))
				{
					this.OnServiceType_IdChanging(value);
					this.SendPropertyChanging();
					this._ServiceType_Id = value;
					this.SendPropertyChanged("ServiceType_Id");
					this.OnServiceType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleName", DbType="NVarChar(100)")]
		public string TitleName
		{
			get
			{
				return this._TitleName;
			}
			set
			{
				if ((this._TitleName != value))
				{
					this.OnTitleNameChanging(value);
					this.SendPropertyChanging();
					this._TitleName = value;
					this.SendPropertyChanged("TitleName");
					this.OnTitleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceType", DbType="Int")]
		public System.Nullable<int> PriceType
		{
			get
			{
				return this._PriceType;
			}
			set
			{
				if ((this._PriceType != value))
				{
					this.OnPriceTypeChanging(value);
					this.SendPropertyChanging();
					this._PriceType = value;
					this.SendPropertyChanged("PriceType");
					this.OnPriceTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ServiceType")]
	public partial class TBL_ServiceType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Id;
		
		private string _TitleName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(short value);
    partial void OnIdChanged();
    partial void OnTitleNameChanging(string value);
    partial void OnTitleNameChanged();
    #endregion
		
		public TBL_ServiceType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleName", DbType="NVarChar(100)")]
		public string TitleName
		{
			get
			{
				return this._TitleName;
			}
			set
			{
				if ((this._TitleName != value))
				{
					this.OnTitleNameChanging(value);
					this.SendPropertyChanging();
					this._TitleName = value;
					this.SendPropertyChanged("TitleName");
					this.OnTitleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ServiceHealthCare")]
	public partial class TBL_ServiceHealthCare : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _VisitHealthCare_Id;
		
		private int _ServiceTypeDsc_Id;
		
		private System.Nullable<int> _ServiceTypeDscFew;
		
		private System.Nullable<int> _PriceType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVisitHealthCare_IdChanging(long value);
    partial void OnVisitHealthCare_IdChanged();
    partial void OnServiceTypeDsc_IdChanging(int value);
    partial void OnServiceTypeDsc_IdChanged();
    partial void OnServiceTypeDscFewChanging(System.Nullable<int> value);
    partial void OnServiceTypeDscFewChanged();
    partial void OnPriceTypeChanging(System.Nullable<int> value);
    partial void OnPriceTypeChanged();
    #endregion
		
		public TBL_ServiceHealthCare()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitHealthCare_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long VisitHealthCare_Id
		{
			get
			{
				return this._VisitHealthCare_Id;
			}
			set
			{
				if ((this._VisitHealthCare_Id != value))
				{
					this.OnVisitHealthCare_IdChanging(value);
					this.SendPropertyChanging();
					this._VisitHealthCare_Id = value;
					this.SendPropertyChanged("VisitHealthCare_Id");
					this.OnVisitHealthCare_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeDsc_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ServiceTypeDsc_Id
		{
			get
			{
				return this._ServiceTypeDsc_Id;
			}
			set
			{
				if ((this._ServiceTypeDsc_Id != value))
				{
					this.OnServiceTypeDsc_IdChanging(value);
					this.SendPropertyChanging();
					this._ServiceTypeDsc_Id = value;
					this.SendPropertyChanged("ServiceTypeDsc_Id");
					this.OnServiceTypeDsc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeDscFew", DbType="Int")]
		public System.Nullable<int> ServiceTypeDscFew
		{
			get
			{
				return this._ServiceTypeDscFew;
			}
			set
			{
				if ((this._ServiceTypeDscFew != value))
				{
					this.OnServiceTypeDscFewChanging(value);
					this.SendPropertyChanging();
					this._ServiceTypeDscFew = value;
					this.SendPropertyChanged("ServiceTypeDscFew");
					this.OnServiceTypeDscFewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceType", DbType="Int")]
		public System.Nullable<int> PriceType
		{
			get
			{
				return this._PriceType;
			}
			set
			{
				if ((this._PriceType != value))
				{
					this.OnPriceTypeChanging(value);
					this.SendPropertyChanging();
					this._PriceType = value;
					this.SendPropertyChanged("PriceType");
					this.OnPriceTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_ServiceHealthCare")]
	public partial class VW_ServiceHealthCare
	{
		
		private long _VisitHealthCare_Id;
		
		private int _ServiceTypeDsc_Id;
		
		private System.Nullable<int> _ServiceTypeDscFew;
		
		private System.Nullable<int> _PriceType;
		
		private string _ServiceTypeDscName;
		
		private System.Nullable<int> _ServiceTypeDscPriceType;
		
		private string _ServiceTypeName;
		
		public VW_ServiceHealthCare()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitHealthCare_Id", DbType="BigInt NOT NULL")]
		public long VisitHealthCare_Id
		{
			get
			{
				return this._VisitHealthCare_Id;
			}
			set
			{
				if ((this._VisitHealthCare_Id != value))
				{
					this._VisitHealthCare_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeDsc_Id", DbType="Int NOT NULL")]
		public int ServiceTypeDsc_Id
		{
			get
			{
				return this._ServiceTypeDsc_Id;
			}
			set
			{
				if ((this._ServiceTypeDsc_Id != value))
				{
					this._ServiceTypeDsc_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeDscFew", DbType="Int")]
		public System.Nullable<int> ServiceTypeDscFew
		{
			get
			{
				return this._ServiceTypeDscFew;
			}
			set
			{
				if ((this._ServiceTypeDscFew != value))
				{
					this._ServiceTypeDscFew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceType", DbType="Int")]
		public System.Nullable<int> PriceType
		{
			get
			{
				return this._PriceType;
			}
			set
			{
				if ((this._PriceType != value))
				{
					this._PriceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeDscName", DbType="NVarChar(100)")]
		public string ServiceTypeDscName
		{
			get
			{
				return this._ServiceTypeDscName;
			}
			set
			{
				if ((this._ServiceTypeDscName != value))
				{
					this._ServiceTypeDscName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeDscPriceType", DbType="Int")]
		public System.Nullable<int> ServiceTypeDscPriceType
		{
			get
			{
				return this._ServiceTypeDscPriceType;
			}
			set
			{
				if ((this._ServiceTypeDscPriceType != value))
				{
					this._ServiceTypeDscPriceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeName", DbType="NVarChar(100)")]
		public string ServiceTypeName
		{
			get
			{
				return this._ServiceTypeName;
			}
			set
			{
				if ((this._ServiceTypeName != value))
				{
					this._ServiceTypeName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_ServiceType")]
	public partial class VW_ServiceType
	{
		
		private short _Id;
		
		private string _TitleName;
		
		public VW_ServiceType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public short Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleName", DbType="NVarChar(100)")]
		public string TitleName
		{
			get
			{
				return this._TitleName;
			}
			set
			{
				if ((this._TitleName != value))
				{
					this._TitleName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_ServiceTypeDsc")]
	public partial class VW_ServiceTypeDsc
	{
		
		private int _Id;
		
		private System.Nullable<short> _ServiceType_Id;
		
		private string _TitleName;
		
		private System.Nullable<int> _PriceType;
		
		private string _ServiceTypeName;
		
		public VW_ServiceTypeDsc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceType_Id", DbType="SmallInt")]
		public System.Nullable<short> ServiceType_Id
		{
			get
			{
				return this._ServiceType_Id;
			}
			set
			{
				if ((this._ServiceType_Id != value))
				{
					this._ServiceType_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleName", DbType="NVarChar(100)")]
		public string TitleName
		{
			get
			{
				return this._TitleName;
			}
			set
			{
				if ((this._TitleName != value))
				{
					this._TitleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceType", DbType="Int")]
		public System.Nullable<int> PriceType
		{
			get
			{
				return this._PriceType;
			}
			set
			{
				if ((this._PriceType != value))
				{
					this._PriceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeName", DbType="NVarChar(100)")]
		public string ServiceTypeName
		{
			get
			{
				return this._ServiceTypeName;
			}
			set
			{
				if ((this._ServiceTypeName != value))
				{
					this._ServiceTypeName = value;
				}
			}
		}
	}
	
	public partial class SP_ServiceHealthCareReportForDetailSumResult
	{
		
		private System.Nullable<long> _کد_بهیاری;
		
		private System.Nullable<int> _تعداد_خدمت;
		
		private System.Nullable<int> _مبلغ_خدمت;
		
		private string _شرح_نوع_خدمت;
		
		private string _شرح_خدمت;
		
		private string _ماه;
		
		private int _کد_بیمار;
		
		private System.Nullable<int> _کد_بهیار;
		
		public SP_ServiceHealthCareReportForDetailSumResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بهیاری]", Storage="_کد_بهیاری", DbType="BigInt")]
		public System.Nullable<long> کد_بهیاری
		{
			get
			{
				return this._کد_بهیاری;
			}
			set
			{
				if ((this._کد_بهیاری != value))
				{
					this._کد_بهیاری = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعداد خدمت]", Storage="_تعداد_خدمت", DbType="Int")]
		public System.Nullable<int> تعداد_خدمت
		{
			get
			{
				return this._تعداد_خدمت;
			}
			set
			{
				if ((this._تعداد_خدمت != value))
				{
					this._تعداد_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[مبلغ خدمت]", Storage="_مبلغ_خدمت", DbType="Int")]
		public System.Nullable<int> مبلغ_خدمت
		{
			get
			{
				return this._مبلغ_خدمت;
			}
			set
			{
				if ((this._مبلغ_خدمت != value))
				{
					this._مبلغ_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شرح نوع خدمت]", Storage="_شرح_نوع_خدمت", DbType="VarChar(100)")]
		public string شرح_نوع_خدمت
		{
			get
			{
				return this._شرح_نوع_خدمت;
			}
			set
			{
				if ((this._شرح_نوع_خدمت != value))
				{
					this._شرح_نوع_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شرح خدمت]", Storage="_شرح_خدمت", DbType="VarChar(100)")]
		public string شرح_خدمت
		{
			get
			{
				return this._شرح_خدمت;
			}
			set
			{
				if ((this._شرح_خدمت != value))
				{
					this._شرح_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ماه", DbType="VarChar(7)")]
		public string ماه
		{
			get
			{
				return this._ماه;
			}
			set
			{
				if ((this._ماه != value))
				{
					this._ماه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بیمار]", Storage="_کد_بیمار", DbType="Int NOT NULL")]
		public int کد_بیمار
		{
			get
			{
				return this._کد_بیمار;
			}
			set
			{
				if ((this._کد_بیمار != value))
				{
					this._کد_بیمار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بهیار]", Storage="_کد_بهیار", DbType="Int")]
		public System.Nullable<int> کد_بهیار
		{
			get
			{
				return this._کد_بهیار;
			}
			set
			{
				if ((this._کد_بهیار != value))
				{
					this._کد_بهیار = value;
				}
			}
		}
	}
	
	public partial class SP_ServiceHealthCareReportForDetailResult
	{
		
		private long _کد_بهیاری;
		
		private System.Nullable<int> _تعداد_خدمت;
		
		private System.Nullable<int> _مبلغ_خدمت;
		
		private string _شرح_نوع_خدمت;
		
		private string _شرح_خدمت;
		
		private string _ماه;
		
		private int _کد_بیمار;
		
		private System.Nullable<int> _کد_بهیار;
		
		public SP_ServiceHealthCareReportForDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بهیاری]", Storage="_کد_بهیاری", DbType="BigInt NOT NULL")]
		public long کد_بهیاری
		{
			get
			{
				return this._کد_بهیاری;
			}
			set
			{
				if ((this._کد_بهیاری != value))
				{
					this._کد_بهیاری = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعداد خدمت]", Storage="_تعداد_خدمت", DbType="Int")]
		public System.Nullable<int> تعداد_خدمت
		{
			get
			{
				return this._تعداد_خدمت;
			}
			set
			{
				if ((this._تعداد_خدمت != value))
				{
					this._تعداد_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[مبلغ خدمت]", Storage="_مبلغ_خدمت", DbType="Int")]
		public System.Nullable<int> مبلغ_خدمت
		{
			get
			{
				return this._مبلغ_خدمت;
			}
			set
			{
				if ((this._مبلغ_خدمت != value))
				{
					this._مبلغ_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شرح نوع خدمت]", Storage="_شرح_نوع_خدمت", DbType="VarChar(100)")]
		public string شرح_نوع_خدمت
		{
			get
			{
				return this._شرح_نوع_خدمت;
			}
			set
			{
				if ((this._شرح_نوع_خدمت != value))
				{
					this._شرح_نوع_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شرح خدمت]", Storage="_شرح_خدمت", DbType="VarChar(100)")]
		public string شرح_خدمت
		{
			get
			{
				return this._شرح_خدمت;
			}
			set
			{
				if ((this._شرح_خدمت != value))
				{
					this._شرح_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ماه", DbType="VarChar(7)")]
		public string ماه
		{
			get
			{
				return this._ماه;
			}
			set
			{
				if ((this._ماه != value))
				{
					this._ماه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بیمار]", Storage="_کد_بیمار", DbType="Int NOT NULL")]
		public int کد_بیمار
		{
			get
			{
				return this._کد_بیمار;
			}
			set
			{
				if ((this._کد_بیمار != value))
				{
					this._کد_بیمار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بهیار]", Storage="_کد_بهیار", DbType="Int")]
		public System.Nullable<int> کد_بهیار
		{
			get
			{
				return this._کد_بهیار;
			}
			set
			{
				if ((this._کد_بهیار != value))
				{
					this._کد_بهیار = value;
				}
			}
		}
	}
	
	public partial class SP_ServiceHealthCareReportForDetailWithGroupResult
	{
		
		private System.Nullable<long> _کد_بهیاری;
		
		private System.Nullable<int> _تعداد_خدمت;
		
		private System.Nullable<int> _مبلغ_خدمت;
		
		private string _شرح_نوع_خدمت;
		
		private string _شرح_خدمت;
		
		private string _ماه;
		
		private int _کد_بیمار;
		
		private System.Nullable<int> _کد_بهیار;
		
		private string _تاریخ_بهیاری;
		
		public SP_ServiceHealthCareReportForDetailWithGroupResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بهیاری]", Storage="_کد_بهیاری", DbType="BigInt")]
		public System.Nullable<long> کد_بهیاری
		{
			get
			{
				return this._کد_بهیاری;
			}
			set
			{
				if ((this._کد_بهیاری != value))
				{
					this._کد_بهیاری = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تعداد خدمت]", Storage="_تعداد_خدمت", DbType="Int")]
		public System.Nullable<int> تعداد_خدمت
		{
			get
			{
				return this._تعداد_خدمت;
			}
			set
			{
				if ((this._تعداد_خدمت != value))
				{
					this._تعداد_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[مبلغ خدمت]", Storage="_مبلغ_خدمت", DbType="Int")]
		public System.Nullable<int> مبلغ_خدمت
		{
			get
			{
				return this._مبلغ_خدمت;
			}
			set
			{
				if ((this._مبلغ_خدمت != value))
				{
					this._مبلغ_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شرح نوع خدمت]", Storage="_شرح_نوع_خدمت", DbType="VarChar(100)")]
		public string شرح_نوع_خدمت
		{
			get
			{
				return this._شرح_نوع_خدمت;
			}
			set
			{
				if ((this._شرح_نوع_خدمت != value))
				{
					this._شرح_نوع_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[شرح خدمت]", Storage="_شرح_خدمت", DbType="VarChar(100)")]
		public string شرح_خدمت
		{
			get
			{
				return this._شرح_خدمت;
			}
			set
			{
				if ((this._شرح_خدمت != value))
				{
					this._شرح_خدمت = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ماه", DbType="VarChar(7)")]
		public string ماه
		{
			get
			{
				return this._ماه;
			}
			set
			{
				if ((this._ماه != value))
				{
					this._ماه = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بیمار]", Storage="_کد_بیمار", DbType="Int NOT NULL")]
		public int کد_بیمار
		{
			get
			{
				return this._کد_بیمار;
			}
			set
			{
				if ((this._کد_بیمار != value))
				{
					this._کد_بیمار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[کد بهیار]", Storage="_کد_بهیار", DbType="Int")]
		public System.Nullable<int> کد_بهیار
		{
			get
			{
				return this._کد_بهیار;
			}
			set
			{
				if ((this._کد_بهیار != value))
				{
					this._کد_بهیار = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[تاریخ بهیاری]", Storage="_تاریخ_بهیاری", DbType="VarChar(10)")]
		public string تاریخ_بهیاری
		{
			get
			{
				return this._تاریخ_بهیاری;
			}
			set
			{
				if ((this._تاریخ_بهیاری != value))
				{
					this._تاریخ_بهیاری = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
