<?xml version="1.0" encoding="utf-8"?><Database Name="PhysiotherapyCare" Class="DataClassesKeyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=PhysiotherapyCare;Integrated Security=True" SettingsObjectName="MKH.SMS.Model.Properties.Settings" SettingsPropertyName="PhysiotherapyCareConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Base.TBL_Key" Member="TBL_Keys">
    <Type Name="TBL_Key">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Base.VW_Key" Member="VW_Keys">
    <Type Name="VW_Key">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="Base.SP_KeyDelete" Method="SP_KeyDelete">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(2000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Base.SP_KeyInsert" Method="SP_KeyInsert">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="TitleName" Parameter="titleName" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Base.SP_KeyUpdate" Method="SP_KeyUpdate">
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="TitleName" Parameter="titleName" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>