<?xml version="1.0" encoding="utf-8"?><Database Name="PhysiotherapyCare" Class="DataClassesVisitPatientPhysiotherapyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=PhysiotherapyCare;Integrated Security=True" SettingsObjectName="PhysiotherapyCare.Model.Properties.Settings" SettingsPropertyName="PhysiotherapyCareConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VW_VisitPatientPhysiotherapy" Member="VW_VisitPatientPhysiotherapies">
    <Type Name="VW_VisitPatientPhysiotherapy">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Patient_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LetterNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LetterDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Doctor_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VisitFew" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BeginDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EndDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DoctorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoctorFamily" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PatientProblem" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PhysiotherapyType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="DosiersNo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PatientName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PatientFamily" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="IDNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NationalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PatientTypeStr" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="InjuryTypeStr" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="BrithDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BrithCityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PercentState" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CityPart" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InstitutePart" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AddressPart" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TelHome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TelBusiness" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountNo1" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="AccountNo2" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="AccountNo3" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="IssueArchive" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CordinateDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SexStr" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="SingleOrNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BonyadAddEvenStr" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="DoctorsMobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorsTelBusiness" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorsTelHome" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorsEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorsAddress" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DoctorsNationalCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContractNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContractDate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ContractEndDate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LocationPart" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="DoctorPhysioMobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorPhysioTelBusiness" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorPhysioTelHome" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorPhysioEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DoctorPhysioAddress" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DoctorPhysioNationalCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DoctorPhysioContractNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DoctorPhysioContractDate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DoctorPhysioContractEndDate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DoctorPhysioLocationPart" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="VisitStatus_Id" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VisitStatusName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeDateTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UsersNameFamily" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
      <Column Name="VisitFewDoing" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DoctorPhysio_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReciveFileDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DoctorPhysioName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoctorPhysioFamily" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoctorPhysioMedicalCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MonthPhysiotherapy" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MedicalCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CardBankNo1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CardBankNo2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DoctorPrice" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoctorParentsNameFamily" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="DoctorTaxPercent" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BasicInsurance" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompletionInsurance" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoctorBrithDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="StatePart" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BonyadDosier" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CityState" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_VisitPatientPhysiotherapy" Member="TBL_VisitPatientPhysiotherapies">
    <Type Name="TBL_VisitPatientPhysiotherapy">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Patient_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IssueArchive" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LetterNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LetterDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Doctor_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DoctorPhysio_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PatientProblem" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PhysiotherapyType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CordinateDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VisitFew" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VisitFewDoing" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BeginDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EndDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VisitStatus_Id" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ReciveFileDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeDateTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_VisitPatientPhysiotherapyDelete" Method="SP_VisitPatientPhysiotherapyDelete">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(2000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_VisitPatientPhysiotherapyReport" Method="SP_VisitPatientPhysiotherapyReport">
    <Parameter Name="DateStart" Parameter="dateStart" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DateEnd" Parameter="dateEnd" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MonthSet" Parameter="monthSet" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="SP_VisitPatientPhysiotherapyReportResult">
      <Column Name="[کد سرتیم فیزیوتراپ]" Member="کد_سرتیم_فیزیوتراپ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[نام سرتیم فیزیوتراپ]" Member="نام_سرتیم_فیزیوتراپ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[فامیل سرتیم فیزیوتراپ]" Member="فامیل_سرتیم_فیزیوتراپ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ماه" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="[کد ملی]" Member="کد_ملی" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[تلفن مطب]" Member="تلفن_مطب" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="موبایل" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[تلفن منزل]" Member="تلفن_منزل" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[منطقه تحت پوشش]" Member="منطقه_تحت_پوشش" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="[تعداد کل]" Member="تعداد_کل" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[تعدا فرد]" Member="تعدا_فرد" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[تعداد زوج]" Member="تعداد_زوج" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[تعداد بدون عودتی]" Member="تعداد_بدون_عودتی" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[تعداد عودتی]" Member="تعداد_عودتی" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_VisitPatientPhysiotherapyInsert" Method="SP_VisitPatientPhysiotherapyInsert">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="Patient_Id" Parameter="patient_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="IssueArchive" Parameter="issueArchive" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LetterNo" Parameter="letterNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LetterDate" Parameter="letterDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Doctor_Id" Parameter="doctor_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="DoctorPhysio_Id" Parameter="doctorPhysio_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="PatientProblem" Parameter="patientProblem" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="PhysiotherapyType" Parameter="physiotherapyType" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="CordinateDate" Parameter="cordinateDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="VisitFew" Parameter="visitFew" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="VisitFewDoing" Parameter="visitFewDoing" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="BeginDate" Parameter="beginDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="VisitStatus_Id" Parameter="visitStatus_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="ReciveFileDate" Parameter="reciveFileDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ChangeDateTime" Parameter="changeDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_VisitPatientPhysiotherapyUpdate" Method="SP_VisitPatientPhysiotherapyUpdate">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Patient_Id" Parameter="patient_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="IssueArchive" Parameter="issueArchive" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="LetterNo" Parameter="letterNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LetterDate" Parameter="letterDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Doctor_Id" Parameter="doctor_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="DoctorPhysio_Id" Parameter="doctorPhysio_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="PatientProblem" Parameter="patientProblem" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="PhysiotherapyType" Parameter="physiotherapyType" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="CordinateDate" Parameter="cordinateDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="VisitFew" Parameter="visitFew" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="VisitFewDoing" Parameter="visitFewDoing" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="BeginDate" Parameter="beginDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="EndDate" Parameter="endDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="VisitStatus_Id" Parameter="visitStatus_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="ReciveFileDate" Parameter="reciveFileDate" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ChangeDateTime" Parameter="changeDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_VisitPatientPhysiotherapyUpdateWithFieldValue" Method="SP_VisitPatientPhysiotherapyUpdateWithFieldValue">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FieldName" Parameter="fieldName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FieldValue" Parameter="fieldValue" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ChangeDateTime" Parameter="changeDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_VisitPatientPhysiotherapyVisitStatusUpdate" Method="SP_VisitPatientPhysiotherapyVisitStatusUpdate">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="VisitStatus_Id" Parameter="visitStatus_Id" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="User_Id" Parameter="user_Id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ChangeDateTime" Parameter="changeDateTime" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="msgRet" Type="System.String" DbType="VarChar(1000)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>