#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysiotherapyCare.Model.Martyrs
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PhysiotherapyCare")]
	public partial class DataClassesMartyrsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_Martyr(TBL_Martyr instance);
    partial void UpdateTBL_Martyr(TBL_Martyr instance);
    partial void DeleteTBL_Martyr(TBL_Martyr instance);
    #endregion
		
		public DataClassesMartyrsDataContext() : 
				base(global::PhysiotherapyCare.Model.Properties.Settings.Default.PhysiotherapyCareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMartyrsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMartyrsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMartyrsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesMartyrsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_Martyr> TBL_Martyrs
		{
			get
			{
				return this.GetTable<TBL_Martyr>();
			}
		}
		
		public System.Data.Linq.Table<VW_Martyr> VW_Martyrs
		{
			get
			{
				return this.GetTable<VW_Martyr>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MartyrsDelete")]
		public int SP_MartyrsDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrId", DbType="Int")] System.Nullable<int> martyrId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), martyrId, msgRet);
			msgRet = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MartyrsInsert")]
		public int SP_MartyrsInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrId", DbType="Int")] ref System.Nullable<int> martyrId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrNameFamily", DbType="VarChar(500)")] string martyrNameFamily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrFew", DbType="SmallInt")] System.Nullable<short> martyrFew, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo1", DbType="VarChar(20)")] string dosiersNo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode1", DbType="VarChar(10)")] string nationalCode1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrName1", DbType="VarChar(50)")] string martyrName1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate1", DbType="VarChar(20)")] string brithDate1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrDate1", DbType="VarChar(20)")] string martyrDate1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrLocation1", DbType="VarChar(50)")] string martyrLocation1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo2", DbType="VarChar(20)")] string dosiersNo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode2", DbType="VarChar(10)")] string nationalCode2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrName2", DbType="VarChar(50)")] string martyrName2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate2", DbType="VarChar(20)")] string brithDate2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrDate2", DbType="VarChar(20)")] string martyrDate2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrLocation2", DbType="VarChar(50)")] string martyrLocation2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo3", DbType="VarChar(20)")] string dosiersNo3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode3", DbType="VarChar(10)")] string nationalCode3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrName3", DbType="VarChar(50)")] string martyrName3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate3", DbType="VarChar(20)")] string brithDate3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrDate3", DbType="VarChar(20)")] string martyrDate3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrLocation3", DbType="VarChar(50)")] string martyrLocation3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), martyrId, martyrNameFamily, martyrFew, dosiersNo1, nationalCode1, martyrName1, brithDate1, martyrDate1, martyrLocation1, dosiersNo2, nationalCode2, martyrName2, brithDate2, martyrDate2, martyrLocation2, dosiersNo3, nationalCode3, martyrName3, brithDate3, martyrDate3, martyrLocation3, description, msgRet);
			martyrId = ((System.Nullable<int>)(result.GetParameterValue(0)));
			msgRet = ((string)(result.GetParameterValue(22)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MartyrsUpdate")]
		public int SP_MartyrsUpdate(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrId", DbType="Int")] System.Nullable<int> martyrId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrNameFamily", DbType="VarChar(500)")] string martyrNameFamily, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrFew", DbType="SmallInt")] System.Nullable<short> martyrFew, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo1", DbType="VarChar(20)")] string dosiersNo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode1", DbType="VarChar(10)")] string nationalCode1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrName1", DbType="VarChar(50)")] string martyrName1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate1", DbType="VarChar(20)")] string brithDate1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrDate1", DbType="VarChar(20)")] string martyrDate1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrLocation1", DbType="VarChar(50)")] string martyrLocation1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo2", DbType="VarChar(20)")] string dosiersNo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode2", DbType="VarChar(10)")] string nationalCode2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrName2", DbType="VarChar(50)")] string martyrName2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate2", DbType="VarChar(20)")] string brithDate2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrDate2", DbType="VarChar(20)")] string martyrDate2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrLocation2", DbType="VarChar(50)")] string martyrLocation2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DosiersNo3", DbType="VarChar(20)")] string dosiersNo3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalCode3", DbType="VarChar(10)")] string nationalCode3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrName3", DbType="VarChar(50)")] string martyrName3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrithDate3", DbType="VarChar(20)")] string brithDate3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrDate3", DbType="VarChar(20)")] string martyrDate3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MartyrLocation3", DbType="VarChar(50)")] string martyrLocation3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(1000)")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1000)")] ref string msgRet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), martyrId, martyrNameFamily, martyrFew, dosiersNo1, nationalCode1, martyrName1, brithDate1, martyrDate1, martyrLocation1, dosiersNo2, nationalCode2, martyrName2, brithDate2, martyrDate2, martyrLocation2, dosiersNo3, nationalCode3, martyrName3, brithDate3, martyrDate3, martyrLocation3, description, msgRet);
			msgRet = ((string)(result.GetParameterValue(22)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Martyrs")]
	public partial class TBL_Martyr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MartyrId;
		
		private string _MartyrNameFamily;
		
		private System.Nullable<short> _MartyrFew;
		
		private string _DosiersNo1;
		
		private string _NationalCode1;
		
		private string _MartyrName1;
		
		private string _BrithDate1;
		
		private string _MartyrDate1;
		
		private string _MartyrLocation1;
		
		private string _DosiersNo2;
		
		private string _NationalCode2;
		
		private string _MartyrName2;
		
		private string _BrithDate2;
		
		private string _MartyrDate2;
		
		private string _MartyrLocation2;
		
		private string _DosiersNo3;
		
		private string _NationalCode3;
		
		private string _MartyrName3;
		
		private string _BrithDate3;
		
		private string _MartyrDate3;
		
		private string _MartyrLocation3;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMartyrIdChanging(int value);
    partial void OnMartyrIdChanged();
    partial void OnMartyrNameFamilyChanging(string value);
    partial void OnMartyrNameFamilyChanged();
    partial void OnMartyrFewChanging(System.Nullable<short> value);
    partial void OnMartyrFewChanged();
    partial void OnDosiersNo1Changing(string value);
    partial void OnDosiersNo1Changed();
    partial void OnNationalCode1Changing(string value);
    partial void OnNationalCode1Changed();
    partial void OnMartyrName1Changing(string value);
    partial void OnMartyrName1Changed();
    partial void OnBrithDate1Changing(string value);
    partial void OnBrithDate1Changed();
    partial void OnMartyrDate1Changing(string value);
    partial void OnMartyrDate1Changed();
    partial void OnMartyrLocation1Changing(string value);
    partial void OnMartyrLocation1Changed();
    partial void OnDosiersNo2Changing(string value);
    partial void OnDosiersNo2Changed();
    partial void OnNationalCode2Changing(string value);
    partial void OnNationalCode2Changed();
    partial void OnMartyrName2Changing(string value);
    partial void OnMartyrName2Changed();
    partial void OnBrithDate2Changing(string value);
    partial void OnBrithDate2Changed();
    partial void OnMartyrDate2Changing(string value);
    partial void OnMartyrDate2Changed();
    partial void OnMartyrLocation2Changing(string value);
    partial void OnMartyrLocation2Changed();
    partial void OnDosiersNo3Changing(string value);
    partial void OnDosiersNo3Changed();
    partial void OnNationalCode3Changing(string value);
    partial void OnNationalCode3Changed();
    partial void OnMartyrName3Changing(string value);
    partial void OnMartyrName3Changed();
    partial void OnBrithDate3Changing(string value);
    partial void OnBrithDate3Changed();
    partial void OnMartyrDate3Changing(string value);
    partial void OnMartyrDate3Changed();
    partial void OnMartyrLocation3Changing(string value);
    partial void OnMartyrLocation3Changed();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TBL_Martyr()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MartyrId
		{
			get
			{
				return this._MartyrId;
			}
			set
			{
				if ((this._MartyrId != value))
				{
					this.OnMartyrIdChanging(value);
					this.SendPropertyChanging();
					this._MartyrId = value;
					this.SendPropertyChanged("MartyrId");
					this.OnMartyrIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrNameFamily", DbType="VarChar(500)")]
		public string MartyrNameFamily
		{
			get
			{
				return this._MartyrNameFamily;
			}
			set
			{
				if ((this._MartyrNameFamily != value))
				{
					this.OnMartyrNameFamilyChanging(value);
					this.SendPropertyChanging();
					this._MartyrNameFamily = value;
					this.SendPropertyChanged("MartyrNameFamily");
					this.OnMartyrNameFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrFew", DbType="SmallInt")]
		public System.Nullable<short> MartyrFew
		{
			get
			{
				return this._MartyrFew;
			}
			set
			{
				if ((this._MartyrFew != value))
				{
					this.OnMartyrFewChanging(value);
					this.SendPropertyChanging();
					this._MartyrFew = value;
					this.SendPropertyChanged("MartyrFew");
					this.OnMartyrFewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo1", DbType="VarChar(20)")]
		public string DosiersNo1
		{
			get
			{
				return this._DosiersNo1;
			}
			set
			{
				if ((this._DosiersNo1 != value))
				{
					this.OnDosiersNo1Changing(value);
					this.SendPropertyChanging();
					this._DosiersNo1 = value;
					this.SendPropertyChanged("DosiersNo1");
					this.OnDosiersNo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode1", DbType="VarChar(10)")]
		public string NationalCode1
		{
			get
			{
				return this._NationalCode1;
			}
			set
			{
				if ((this._NationalCode1 != value))
				{
					this.OnNationalCode1Changing(value);
					this.SendPropertyChanging();
					this._NationalCode1 = value;
					this.SendPropertyChanged("NationalCode1");
					this.OnNationalCode1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrName1", DbType="VarChar(50)")]
		public string MartyrName1
		{
			get
			{
				return this._MartyrName1;
			}
			set
			{
				if ((this._MartyrName1 != value))
				{
					this.OnMartyrName1Changing(value);
					this.SendPropertyChanging();
					this._MartyrName1 = value;
					this.SendPropertyChanged("MartyrName1");
					this.OnMartyrName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate1", DbType="VarChar(20)")]
		public string BrithDate1
		{
			get
			{
				return this._BrithDate1;
			}
			set
			{
				if ((this._BrithDate1 != value))
				{
					this.OnBrithDate1Changing(value);
					this.SendPropertyChanging();
					this._BrithDate1 = value;
					this.SendPropertyChanged("BrithDate1");
					this.OnBrithDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrDate1", DbType="VarChar(20)")]
		public string MartyrDate1
		{
			get
			{
				return this._MartyrDate1;
			}
			set
			{
				if ((this._MartyrDate1 != value))
				{
					this.OnMartyrDate1Changing(value);
					this.SendPropertyChanging();
					this._MartyrDate1 = value;
					this.SendPropertyChanged("MartyrDate1");
					this.OnMartyrDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrLocation1", DbType="VarChar(50)")]
		public string MartyrLocation1
		{
			get
			{
				return this._MartyrLocation1;
			}
			set
			{
				if ((this._MartyrLocation1 != value))
				{
					this.OnMartyrLocation1Changing(value);
					this.SendPropertyChanging();
					this._MartyrLocation1 = value;
					this.SendPropertyChanged("MartyrLocation1");
					this.OnMartyrLocation1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo2", DbType="VarChar(20)")]
		public string DosiersNo2
		{
			get
			{
				return this._DosiersNo2;
			}
			set
			{
				if ((this._DosiersNo2 != value))
				{
					this.OnDosiersNo2Changing(value);
					this.SendPropertyChanging();
					this._DosiersNo2 = value;
					this.SendPropertyChanged("DosiersNo2");
					this.OnDosiersNo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode2", DbType="VarChar(10)")]
		public string NationalCode2
		{
			get
			{
				return this._NationalCode2;
			}
			set
			{
				if ((this._NationalCode2 != value))
				{
					this.OnNationalCode2Changing(value);
					this.SendPropertyChanging();
					this._NationalCode2 = value;
					this.SendPropertyChanged("NationalCode2");
					this.OnNationalCode2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrName2", DbType="VarChar(50)")]
		public string MartyrName2
		{
			get
			{
				return this._MartyrName2;
			}
			set
			{
				if ((this._MartyrName2 != value))
				{
					this.OnMartyrName2Changing(value);
					this.SendPropertyChanging();
					this._MartyrName2 = value;
					this.SendPropertyChanged("MartyrName2");
					this.OnMartyrName2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate2", DbType="VarChar(20)")]
		public string BrithDate2
		{
			get
			{
				return this._BrithDate2;
			}
			set
			{
				if ((this._BrithDate2 != value))
				{
					this.OnBrithDate2Changing(value);
					this.SendPropertyChanging();
					this._BrithDate2 = value;
					this.SendPropertyChanged("BrithDate2");
					this.OnBrithDate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrDate2", DbType="VarChar(20)")]
		public string MartyrDate2
		{
			get
			{
				return this._MartyrDate2;
			}
			set
			{
				if ((this._MartyrDate2 != value))
				{
					this.OnMartyrDate2Changing(value);
					this.SendPropertyChanging();
					this._MartyrDate2 = value;
					this.SendPropertyChanged("MartyrDate2");
					this.OnMartyrDate2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrLocation2", DbType="VarChar(50)")]
		public string MartyrLocation2
		{
			get
			{
				return this._MartyrLocation2;
			}
			set
			{
				if ((this._MartyrLocation2 != value))
				{
					this.OnMartyrLocation2Changing(value);
					this.SendPropertyChanging();
					this._MartyrLocation2 = value;
					this.SendPropertyChanged("MartyrLocation2");
					this.OnMartyrLocation2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo3", DbType="VarChar(20)")]
		public string DosiersNo3
		{
			get
			{
				return this._DosiersNo3;
			}
			set
			{
				if ((this._DosiersNo3 != value))
				{
					this.OnDosiersNo3Changing(value);
					this.SendPropertyChanging();
					this._DosiersNo3 = value;
					this.SendPropertyChanged("DosiersNo3");
					this.OnDosiersNo3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode3", DbType="VarChar(10)")]
		public string NationalCode3
		{
			get
			{
				return this._NationalCode3;
			}
			set
			{
				if ((this._NationalCode3 != value))
				{
					this.OnNationalCode3Changing(value);
					this.SendPropertyChanging();
					this._NationalCode3 = value;
					this.SendPropertyChanged("NationalCode3");
					this.OnNationalCode3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrName3", DbType="VarChar(50)")]
		public string MartyrName3
		{
			get
			{
				return this._MartyrName3;
			}
			set
			{
				if ((this._MartyrName3 != value))
				{
					this.OnMartyrName3Changing(value);
					this.SendPropertyChanging();
					this._MartyrName3 = value;
					this.SendPropertyChanged("MartyrName3");
					this.OnMartyrName3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate3", DbType="VarChar(20)")]
		public string BrithDate3
		{
			get
			{
				return this._BrithDate3;
			}
			set
			{
				if ((this._BrithDate3 != value))
				{
					this.OnBrithDate3Changing(value);
					this.SendPropertyChanging();
					this._BrithDate3 = value;
					this.SendPropertyChanged("BrithDate3");
					this.OnBrithDate3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrDate3", DbType="VarChar(20)")]
		public string MartyrDate3
		{
			get
			{
				return this._MartyrDate3;
			}
			set
			{
				if ((this._MartyrDate3 != value))
				{
					this.OnMartyrDate3Changing(value);
					this.SendPropertyChanging();
					this._MartyrDate3 = value;
					this.SendPropertyChanged("MartyrDate3");
					this.OnMartyrDate3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrLocation3", DbType="VarChar(50)")]
		public string MartyrLocation3
		{
			get
			{
				return this._MartyrLocation3;
			}
			set
			{
				if ((this._MartyrLocation3 != value))
				{
					this.OnMartyrLocation3Changing(value);
					this.SendPropertyChanging();
					this._MartyrLocation3 = value;
					this.SendPropertyChanged("MartyrLocation3");
					this.OnMartyrLocation3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_Martyrs")]
	public partial class VW_Martyr
	{
		
		private int _MartyrId;
		
		private string _MartyrNameFamily;
		
		private System.Nullable<short> _MartyrFew;
		
		private string _DosiersNo1;
		
		private string _NationalCode1;
		
		private string _MartyrName1;
		
		private string _BrithDate1;
		
		private string _MartyrDate1;
		
		private string _MartyrLocation1;
		
		private string _DosiersNo2;
		
		private string _NationalCode2;
		
		private string _MartyrName2;
		
		private string _BrithDate2;
		
		private string _MartyrDate2;
		
		private string _MartyrLocation2;
		
		private string _DosiersNo3;
		
		private string _NationalCode3;
		
		private string _MartyrName3;
		
		private string _BrithDate3;
		
		private string _MartyrDate3;
		
		private string _MartyrLocation3;
		
		private string _Description;
		
		public VW_Martyr()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MartyrId
		{
			get
			{
				return this._MartyrId;
			}
			set
			{
				if ((this._MartyrId != value))
				{
					this._MartyrId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrNameFamily", DbType="VarChar(500)")]
		public string MartyrNameFamily
		{
			get
			{
				return this._MartyrNameFamily;
			}
			set
			{
				if ((this._MartyrNameFamily != value))
				{
					this._MartyrNameFamily = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrFew", DbType="SmallInt")]
		public System.Nullable<short> MartyrFew
		{
			get
			{
				return this._MartyrFew;
			}
			set
			{
				if ((this._MartyrFew != value))
				{
					this._MartyrFew = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo1", DbType="VarChar(20)")]
		public string DosiersNo1
		{
			get
			{
				return this._DosiersNo1;
			}
			set
			{
				if ((this._DosiersNo1 != value))
				{
					this._DosiersNo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode1", DbType="VarChar(10)")]
		public string NationalCode1
		{
			get
			{
				return this._NationalCode1;
			}
			set
			{
				if ((this._NationalCode1 != value))
				{
					this._NationalCode1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrName1", DbType="VarChar(50)")]
		public string MartyrName1
		{
			get
			{
				return this._MartyrName1;
			}
			set
			{
				if ((this._MartyrName1 != value))
				{
					this._MartyrName1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate1", DbType="VarChar(20)")]
		public string BrithDate1
		{
			get
			{
				return this._BrithDate1;
			}
			set
			{
				if ((this._BrithDate1 != value))
				{
					this._BrithDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrDate1", DbType="VarChar(20)")]
		public string MartyrDate1
		{
			get
			{
				return this._MartyrDate1;
			}
			set
			{
				if ((this._MartyrDate1 != value))
				{
					this._MartyrDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrLocation1", DbType="VarChar(50)")]
		public string MartyrLocation1
		{
			get
			{
				return this._MartyrLocation1;
			}
			set
			{
				if ((this._MartyrLocation1 != value))
				{
					this._MartyrLocation1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo2", DbType="VarChar(20)")]
		public string DosiersNo2
		{
			get
			{
				return this._DosiersNo2;
			}
			set
			{
				if ((this._DosiersNo2 != value))
				{
					this._DosiersNo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode2", DbType="VarChar(10)")]
		public string NationalCode2
		{
			get
			{
				return this._NationalCode2;
			}
			set
			{
				if ((this._NationalCode2 != value))
				{
					this._NationalCode2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrName2", DbType="VarChar(50)")]
		public string MartyrName2
		{
			get
			{
				return this._MartyrName2;
			}
			set
			{
				if ((this._MartyrName2 != value))
				{
					this._MartyrName2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate2", DbType="VarChar(20)")]
		public string BrithDate2
		{
			get
			{
				return this._BrithDate2;
			}
			set
			{
				if ((this._BrithDate2 != value))
				{
					this._BrithDate2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrDate2", DbType="VarChar(20)")]
		public string MartyrDate2
		{
			get
			{
				return this._MartyrDate2;
			}
			set
			{
				if ((this._MartyrDate2 != value))
				{
					this._MartyrDate2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrLocation2", DbType="VarChar(50)")]
		public string MartyrLocation2
		{
			get
			{
				return this._MartyrLocation2;
			}
			set
			{
				if ((this._MartyrLocation2 != value))
				{
					this._MartyrLocation2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DosiersNo3", DbType="VarChar(20)")]
		public string DosiersNo3
		{
			get
			{
				return this._DosiersNo3;
			}
			set
			{
				if ((this._DosiersNo3 != value))
				{
					this._DosiersNo3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalCode3", DbType="VarChar(10)")]
		public string NationalCode3
		{
			get
			{
				return this._NationalCode3;
			}
			set
			{
				if ((this._NationalCode3 != value))
				{
					this._NationalCode3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrName3", DbType="VarChar(50)")]
		public string MartyrName3
		{
			get
			{
				return this._MartyrName3;
			}
			set
			{
				if ((this._MartyrName3 != value))
				{
					this._MartyrName3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrithDate3", DbType="VarChar(20)")]
		public string BrithDate3
		{
			get
			{
				return this._BrithDate3;
			}
			set
			{
				if ((this._BrithDate3 != value))
				{
					this._BrithDate3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrDate3", DbType="VarChar(20)")]
		public string MartyrDate3
		{
			get
			{
				return this._MartyrDate3;
			}
			set
			{
				if ((this._MartyrDate3 != value))
				{
					this._MartyrDate3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MartyrLocation3", DbType="VarChar(50)")]
		public string MartyrLocation3
		{
			get
			{
				return this._MartyrLocation3;
			}
			set
			{
				if ((this._MartyrLocation3 != value))
				{
					this._MartyrLocation3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
